import Link from "next/link";
import { ArrowLeft, BedDouble, Phone, Utensils } from "lucide-react";
import { notFound } from "next/navigation";
import { assignRoomAction, releaseRoomAction, reviewStayAction } from "@/app/admin/operations/actions";
import { getAdminAshrams,getRooms,getStayRequest } from "@/lib/operations/admin-data";
import { hasAdminPermission,requireAdminSession } from "@/lib/admin/data";
export default async function StayDetailPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const s=await requireAdminSession();const[request,ashrams,rooms]=await Promise.all([getStayRequest(s,id),getAdminAshrams(s),getRooms(s)]);if(!request)notFound();const a=ashrams.find(x=>x.id===request.ashram_id);const review=hasAdminPermission(s,"stays.review"),assign=hasAdminPermission(s,"stays.assign_room");const eligible=rooms.filter(r=>r.ashram_id===request.ashram_id&&r.active&&!r.archived_at&&r.capacity>=request.total_members);return <div><Link href="/admin/stays" className="inline-flex min-h-10 items-center gap-2 text-sm font-bold text-primary"><ArrowLeft className="size-4"/> રૂમ અરજીઓ</Link><section className="mt-3 rounded-3xl border border-border bg-white p-5 shadow-sm"><p className="text-xs font-bold text-gold-deep">{request.request_number}</p><h1 className="mt-1 font-serif text-2xl font-bold text-primary">{request.applicant_name}</h1><p className="mt-1 text-sm text-muted-foreground">{a?.name_gu||"આશ્રમ"} • {request.check_in} → {request.check_out} • {request.total_members} સભ્ય</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><a className="rounded-xl bg-surface-soft p-3 font-bold text-primary" href={`tel:${request.mobile}`}><Phone className="mr-2 inline size-4"/>{request.mobile}</a><div className="rounded-xl bg-surface-soft p-3 text-sm font-semibold">સ્થિતિ: {request.status}</div><div className="rounded-xl bg-surface-soft p-3 text-sm sm:col-span-2"><strong>એડ્રેસ:</strong> {request.full_address}</div></div></section>
<section className="mt-5 rounded-3xl border border-border bg-white p-5"><h2 className="font-serif text-xl font-bold text-primary">સાથે આવતા સભ્યો ({request.stay_guests?.length||0})</h2><div className="mt-3 space-y-2">{request.stay_guests?.map(g=><div key={g.id} className="rounded-xl bg-surface-soft p-3 text-sm"><strong>{g.guest_order+1}. {g.full_name}</strong>{g.age!=null?` • ઉંમર ${g.age}`:""}{g.relationship?` • ${g.relationship}`:""}</div>)}</div></section>
<section className="mt-5 rounded-3xl border border-border bg-white p-5"><div className="flex items-center gap-2"><Utensils className="size-5 text-gold-deep"/><h2 className="font-serif text-xl font-bold text-primary">પ્રસાદ / ભોજન</h2></div><p className="mt-2 text-sm text-muted-foreground">{request.takes_prasad?`નાસ્તો ${request.breakfast_count} • બપોર ${request.lunch_count} • રાત્રિ ${request.dinner_count}`:"પ્રસાદ/ભોજન નહીં"}</p></section>
{review?<form action={reviewStayAction} className="mt-5 rounded-3xl border border-border bg-white p-5"><input type="hidden" name="id" value={request.id}/><h2 className="font-serif text-xl font-bold text-primary">અરજી સ્થિતિ</h2><div className="mt-3 grid gap-3 sm:grid-cols-[200px_1fr_auto]"><select className="field" name="status" defaultValue={request.status}>{["new","reviewing","documents_required","waitlisted","approved","room_assigned","checked_in","checked_out","rejected","cancelled"].map(x=><option value={x} key={x}>{x}</option>)}</select><input className="field" name="admin_note" defaultValue={request.admin_note??""} placeholder="આંતરિક નોંધ"/><button className="min-h-11 rounded-xl bg-[#eee7de] px-4 font-bold text-primary">સાચવો</button></div></form>:null}
{assign?<section className="mt-5 rounded-3xl border border-border bg-white p-5"><div className="flex items-center gap-2"><BedDouble className="size-5 text-primary"/><h2 className="font-serif text-xl font-bold text-primary">રૂમ ફાળવણી</h2></div>{request.room_assignments?.filter(x=>!x.released_at).map(x=><form action={releaseRoomAction} key={x.id} className="mt-3 flex items-center gap-3 rounded-xl bg-emerald-50 p-3"><input type="hidden" name="assignment_id" value={x.id}/><input type="hidden" name="stay_request_id" value={request.id}/><span className="flex-1 text-sm font-bold">હાલ રૂમ: {rooms.find(r=>r.id===x.room_id)?.room_number||x.room_id}</span><button className="text-xs font-bold text-red-700">મુક્ત કરો</button></form>)}<form action={assignRoomAction} className="mt-3 flex gap-2"><input type="hidden" name="stay_request_id" value={request.id}/><select className="field" name="room_id" required><option value="">ઉપલબ્ધ રૂમ પસંદ કરો</option>{eligible.map(r=><option key={r.id} value={r.id}>{r.room_number} • capacity {r.capacity}</option>)}</select><button className="min-h-12 shrink-0 rounded-xl bg-primary px-4 font-bold text-white">ફાળવો</button></form></section>:null}</div>}
