import type { Ashram, EventItem, NavItem, Publication, SatsangSeries, SevaActivity } from "@/lib/types";

export const siteName = "શ્રી માધવાનંદ આશ્રમ";
export const invocation = "॥ ૐ શ્રી સચ્ચિદાનંદ પરબ્રહ્મણે નમઃ ॥";
export const youtubeChannel = "https://www.youtube.com/@SachchidanandMadhavanand/";
export const youtubeChannelId = "UCSG8rbkV8b4z-bmm9wLwuTA";

export const satsangSeries: SatsangSeries[] = [
  { id: "nitya-karma", slug: "nitya-karma", titleGu: "દૈનિક નિત્યકર્મ", descriptionGu: "પાઠ અને ઉપાસના", category: "nitya-karma", verified: false },
  { id: "guru-gita", slug: "guru-gita", titleGu: "ગુરુ ગીતા", descriptionGu: "પાઠ અને ગુરુતત્ત્વ", category: "guru-gita", verified: false },
  { id: "katha", slug: "katha", titleGu: "કથા અને જ્ઞાનયજ્ઞ", descriptionGu: "કથા અને આધ્યાત્મિક સ્વાધ્યાય", category: "katha", verified: false },
  { id: "bhajan", slug: "bhajan", titleGu: "સંતવાણી અને ભજન", descriptionGu: "ભક્તિ, સ્તોત્ર અને સ્મરણ", category: "bhajan", verified: false },
  { id: "chaturmas", slug: "chaturmas", titleGu: "ચાતુર્માસ", descriptionGu: "વિશેષ સત્સંગ શ્રેણીઓ", category: "chaturmas", verified: false },
  { id: "latest", slug: "latest", titleGu: "તાજા સત્સંગ", descriptionGu: "અધિકૃત ચેનલના નવા પ્રકાશન", category: "pravachan", verified: true, featured: true },
];

export const navItems: NavItem[] = [
  { label: "ગુરુપરંપરા", href: "/parampara" },
  { label: "આશ્રમ", href: "/ashrams" },
  { label: "સેવા", href: "/activities" },
  { label: "સત્સંગ", href: "/satsang" },
  { label: "પ્રકાશન", href: "/publications" },
  { label: "કાર્યક્રમો", href: "/events" },
  { label: "સંપર્ક", href: "/contact" },
];

const branch = (
  id: string,
  nameGu: string,
  localityGu: string,
  region: Ashram["region"],
  verified = false,
): Ashram => ({
  id,
  slug: id,
  nameGu,
  localityGu,
  region,
  verified,
});

export const ashrams: Ashram[] = [
  {
    id: "surat",
    slug: "surat",
    nameGu: "શ્રી માધવાનંદ આશ્રમ — સુરત",
    nameEn: "Shree Madhavanand Ashram Surat",
    localityGu: "ઉદયનગર-૧, કતારગામ રોડ, સુરત",
    region: "મુખ્ય કેન્દ્ર",
    addressGu: "ઉદયનગર-૧, કતારગામ રોડ, સુરત, ગુજરાત — ૩૯૫૦૦૪",
    phone: "+91 261 2534610",
    verified: true,
    featured: true,
  },
  {
    id: "chanod",
    slug: "chanod",
    nameGu: "શ્રી માધવાનંદ આશ્રમ — ચાણોદ",
    nameEn: "Shree Madhavanand Ashram Chanod",
    localityGu: "દયારામપુરી, તા. ડભોઇ, જી. વડોદરા",
    region: "મધ્ય ગુજરાત",
    addressGu: "દયારામપુરી, ચાણોદ, તા. ડભોઇ, જી. વડોદરા, ગુજરાત — ૩૯૧૧૦૫",
    phone: "+91 2663 233362",
    verified: true,
    featured: true,
  },
  {
    id: "sughad",
    slug: "sughad",
    nameGu: "આંતરરાષ્ટ્રીય શ્રી માધવાનંદ આશ્રમ — સુઘડ",
    nameEn: "International Shree Madhavanand Ashram Sughad",
    localityGu: "ઇન્દિરા બ્રિજ નજીક, કોબા સર્કલ, ગાંધીનગર",
    region: "મધ્ય ગુજરાત",
    addressGu: "ઇન્દિરા બ્રિજ, નર્મદા મુખ્ય કેનાલ નજીક, કોબા સર્કલ, સુઘડ, ગાંધીનગર — ૩૮૨૪૨૪",
    phone: "+91 79 23276151",
    verified: true,
    featured: true,
  },
  {
    id: "bhavnagar",
    slug: "bhavnagar",
    nameGu: "શ્રી માધવાનંદ આશ્રમ — ભાવનગર",
    nameEn: "Shree Madhavanand Ashram Bhavnagar",
    localityGu: "પટેલ પાર્ક, ન્યૂ એરોડ્રમ રોડ, ભાવનગર",
    region: "સૌરાષ્ટ્ર",
    addressGu: "૧૦૮૫ પટેલ પાર્ક, ન્યૂ એરોડ્રમ રોડ, ભાવનગર, ગુજરાત — ૩૬૪૦૦૧",
    phone: "+91 278 2201399",
    verified: true,
    featured: true,
  },
  {
    id: "akru",
    slug: "akru",
    nameGu: "શ્રી માધવાનંદ આશ્રમ — આકરુ",
    nameEn: "Shree Madhavanand Ashram Akru",
    localityGu: "તા. ધંધુકા, જી. અમદાવાદ",
    region: "સૌરાષ્ટ્ર",
    addressGu: "આકરુ, તા. ધંધુકા, જી. અમદાવાદ, ગુજરાત",
    phone: "+91 2713 232633",
    verified: true,
    featured: true,
  },
  {
    id: "haridwar",
    slug: "haridwar",
    nameGu: "શ્રી માધવાનંદ આશ્રમ — હરિદ્વાર",
    nameEn: "Shree Madhavanand Ashram Haridwar",
    localityGu: "દક્ષેશ્વર રોડ, જગજીતપુર, કનખલ",
    region: "ઉત્તર ભારત",
    addressGu: "દક્ષેશ્વર રોડ, જગજીતપુર, કનખલ, હરિદ્વાર, ઉત્તરાખંડ — ૨૪૯૪૦૮",
    phone: "+91 1334 246675",
    verified: true,
    featured: true,
  },
  branch("chamardi", "શ્રી માધવાનંદ આશ્રમ — ચમારડી", "ચમારડી, વલ્લભીપુર", "સૌરાષ્ટ્ર"),
  branch("bhadran", "શ્રી માધવાનંદ આશ્રમ — ભાદરણ", "ભાદરણ, આણંદ", "મધ્ય ગુજરાત"),
  branch("pipaliya-shihor", "શ્રી માધવાનંદ આશ્રમ — પીપળીયા", "પીપળીયા, શિહોર", "સૌરાષ્ટ્ર"),
  branch("dadva", "શ્રી માધવાનંદ આશ્રમ — દડવા", "દડવા, ઉમરાળા", "સૌરાષ્ટ્ર"),
  branch("vastadi", "શ્રી માધવાનંદ આશ્રમ — વસ્તડી", "વસ્તડી, લીંબડી", "સૌરાષ્ટ્ર"),
  branch("limbasi", "શ્રી માધવાનંદ આશ્રમ — લીંબાસી", "લીંબાસી, ખેડા", "મધ્ય ગુજરાત"),
  branch("thasara", "શ્રી માધવાનંદ આશ્રમ — ઠાસરા", "ઠાસરા, ખેડા", "મધ્ય ગુજરાત"),
  branch("pipariya-dhandhuka", "શ્રી માધવાનંદ આશ્રમ — પીપરિયા", "પીપરિયા, ધંધુકા", "સૌરાષ્ટ્ર"),
  branch("nava-navda", "શ્રી માધવાનંદ આશ્રમ — નવા નવડા", "નવા નવડા, ધંધુકા", "સૌરાષ્ટ્ર"),
  branch("chogath", "શ્રી માધવાનંદ આશ્રમ — ચોગઠ", "ચોગઠ, ઉમરાળા", "સૌરાષ્ટ્ર"),
  branch("dambhaliya", "શ્રી માધવાનંદ આશ્રમ — દંભાળિયા", "દંભાળિયા, ઉમરાળા", "સૌરાષ્ટ્ર"),
  branch("paldi-shihor", "શ્રી માધવાનંદ આશ્રમ — પાલડી", "પાલડી, શિહોર", "સૌરાષ્ટ્ર"),
  branch("nana-surka", "શ્રી માધવાનંદ આશ્રમ — નાના સુરકા", "નાના સુરકા, શિહોર", "સૌરાષ્ટ્ર"),
  branch("ghanghli", "શ્રી માધવાનંદ આશ્રમ — ઘાંઘળી", "ઘાંઘળી, શિહોર", "સૌરાષ્ટ્ર"),
  branch("shihor", "શ્રી માધવાનંદ આશ્રમ — શિહોર", "શિહોર", "સૌરાષ્ટ્ર"),
  branch("shivohamnagar", "શ્રી માધવાનંદ આશ્રમ — શિવોહમનગર", "શિવોહમનગર, ભાવનગર", "સૌરાષ્ટ્ર"),
  branch("bhingrad", "શ્રી માધવાનંદ આશ્રમ — ભીંગરાડ", "ભીંગરાડ, દામનગર", "સૌરાષ્ટ્ર"),
  branch("umarala", "શ્રી માધવાનંદ આશ્રમ — ઉમરાળા", "ઉમરાળા", "સૌરાષ્ટ્ર"),
  branch("dharuka", "શ્રી માધવાનંદ આશ્રમ — ધારુકા", "ધારુકા, ઉમરાળા", "સૌરાષ્ટ્ર"),
  branch("bhambhan", "શ્રી માધવાનંદ આશ્રમ — ભંભાણ", "ભંભાણ, બોટાદ", "સૌરાષ્ટ્ર"),
  branch("limbdi", "શ્રી માધવાનંદ આશ્રમ — લીંબડી", "લીંબડી", "સૌરાષ્ટ્ર"),
  branch("joravarnagar", "શ્રી માધવાનંદ આશ્રમ — જોરાવરનગર", "જોરાવરનગર", "સૌરાષ્ટ્ર"),
  branch("virta", "શ્રી માધવાનંદ આશ્રમ — વિરતા", "વિરતા, ચાણસ્મા", "ઉત્તર ગુજરાત"),
  branch("mota-isanpur", "શ્રી માધવાનંદ આશ્રમ — મોટા ઇસણપુર", "મોટા ઇસણપુર, ગાંધીનગર", "ઉત્તર ગુજરાત"),
  branch("kapadvanj", "શ્રી માધવાનંદ આશ્રમ — કપડવંજ", "કપડવંજ", "મધ્ય ગુજરાત"),
  branch("kathlal", "શ્રી માધવાનંદ આશ્રમ — કઠલાલ", "કઠલાલ, કપડવંજ", "મધ્ય ગુજરાત"),
  branch("ojrala", "શ્રી માધવાનંદ આશ્રમ — ઓજરાળા", "ઓજરાળા, ઠાસરા", "મધ્ય ગુજરાત"),
  branch("khandhli", "શ્રી માધવાનંદ આશ્રમ — ખાંધળી", "ખાંધળી, ખેડા", "મધ્ય ગુજરાત"),
  branch("sojitra", "શ્રી માધવાનંદ આશ્રમ — સોજિત્રા", "સોજિત્રા, પેટલાદ", "મધ્ય ગુજરાત"),
  branch("nar", "શ્રી માધવાનંદ આશ્રમ — નાર", "નાર, પેટલાદ", "મધ્ય ગુજરાત"),
  branch("vaddala", "શ્રી માધવાનંદ આશ્રમ — વડદલા", "વડદલા, પેટલાદ", "મધ્ય ગુજરાત"),
  branch("dharmaj", "શ્રી માધવાનંદ આશ્રમ — ધર્મજ", "ધર્મજ, પેટલાદ", "મધ્ય ગુજરાત"),
  branch("palol", "શ્રી માધવાનંદ આશ્રમ — પાલોલ", "પાલોલ, પેટલાદ", "મધ્ય ગુજરાત"),
  branch("aanklav", "શ્રી માધવાનંદ આશ્રમ — આંકલાવ", "આંકલાવ, બોરસદ", "મધ્ય ગુજરાત"),
  branch("kanthariya", "શ્રી માધવાનંદ આશ્રમ — કંથારિયા", "કંથારિયા, બોરસદ", "મધ્ય ગુજરાત"),
  branch("haldari", "શ્રી માધવાનંદ આશ્રમ — હલદરી", "હલદરી, બોરસદ", "મધ્ય ગુજરાત"),
  branch("khadol", "શ્રી માધવાનંદ આશ્રમ — ખડોળ", "ખડોળ, બોરસદ", "મધ્ય ગુજરાત"),
  branch("anand", "શ્રી માધવાનંદ આશ્રમ — આણંદ", "આણંદ", "મધ્ય ગુજરાત"),
  branch("karamsad", "શ્રી માધવાનંદ આશ્રમ — કરમસદ", "કરમસદ, આણંદ", "મધ્ય ગુજરાત"),
  branch("vidyanagar", "શ્રી માધવાનંદ આશ્રમ — વિદ્યાનગર", "વિદ્યાનગર, આણંદ", "મધ્ય ગુજરાત"),
  branch("napad", "શ્રી માધવાનંદ આશ્રમ — નાપાડ", "નાપાડ, આણંદ", "મધ્ય ગુજરાત"),
  branch("mumbai", "શ્રી માધવાનંદ આશ્રમ — મુંબઈ", "મુંબઈ, મહારાષ્ટ્ર", "મહારાષ્ટ્ર"),
  branch("new-jersey", "શ્રી માધવાનંદ આશ્રમ — ન્યૂ જર્સી", "ન્યૂ જર્સી, USA", "વિદેશ"),
  branch("chicago", "શ્રી માધવાનંદ આશ્રમ — શિકાગો", "શિકાગો, USA", "વિદેશ"),
];

export const featuredAshrams = ashrams.filter((ashram) => ashram.featured);

export const events: EventItem[] = [
  {
    id: "daily-satsang",
    slug: "daily-satsang",
    kind: "satsang",
    scheduleType: "recurring",
    eyebrowGu: "નિયમિત સત્સંગ",
    titleGu: "ગુરુ ગીતા પાઠ અને સત્સંગ",
    descriptionGu: "દૈનિક આધ્યાત્મિક અભ્યાસ અને પ્રવચનો માટે અધિકૃત YouTube ચેનલ સાથે જોડાઓ.",
    status: "review",
    verified: false,
  },
  {
    id: "chaturmas",
    slug: "chaturmas",
    kind: "festival",
    scheduleType: "announcement",
    eyebrowGu: "પરંપરા",
    titleGu: "દિવ્ય ચાતુર્માસ સત્સંગ શ્રેણી",
    descriptionGu: "કથા, પાઠ, ભજન અને ગુરુવાણીના કાર્યક્રમોની માહિતી એક જ સ્થળે ઉપલબ્ધ થશે.",
    status: "review",
    verified: false,
  },
];

export const publications: Publication[] = [
  {
    id: "veda-rahasya-june-2017",
    slug: "veda-rahasya-june-2017",
    kind: "veda-rahasya",
    titleGu: "વેદ રહસ્ય",
    editionGu: "જૂન ૨૦૧૭ અંક",
    monthGu: "જૂન",
    year: 2017,
    pdfUrl: "https://omshreemadhavanandji.org/content/pub_vedarahasya/Ved-Rahasya-June-2017.pdf",
    verified: true,
  },
  {
    id: "veda-rahasya-may-2016",
    slug: "veda-rahasya-may-2016",
    kind: "veda-rahasya",
    titleGu: "વેદ રહસ્ય",
    editionGu: "મે ૨૦૧૬ અંક",
    monthGu: "મે",
    year: 2016,
    pdfUrl: "https://www.omshreemadhavanandji.org/content/pub_vedarahasya/Ved-Rahasya-May-2016.pdf",
    verified: true,
  },
  {
    id: "veda-rahasya-july-2014",
    slug: "veda-rahasya-july-2014",
    kind: "veda-rahasya",
    titleGu: "વેદ રહસ્ય",
    editionGu: "જુલાઈ ૨૦૧૪ અંક",
    monthGu: "જુલાઈ",
    year: 2014,
    pdfUrl: "https://www.omshreemadhavanandji.org/content/pub_vedarahasya/Ved-Rahasya-July-2014.pdf",
    verified: true,
  },
];

export const sevaActivities: SevaActivity[] = [
  {
    id: "gau-seva",
    titleGu: "ગૌશાળા અને જીવદયા",
    kickerGu: "ગૌ સેવા એ જ પ્રભુ સેવા",
    descriptionGu: "ગૌમાતાની સંભાળ, ચારો, આરોગ્ય અને જીવદયાની ભાવનાને આશ્રમ જીવનનો જીવંત ભાગ બનાવતી સેવા.",
    icon: "cow",
  },
  {
    id: "medical",
    titleGu: "નિઃશુલ્ક આરોગ્ય સેવા",
    kickerGu: "માનવ સેવા એ જ માધવ સેવા",
    descriptionGu: "આરોગ્ય નિદાન કેમ્પ અને સમાજના જરૂરિયાતમંદ લોકો સુધી ઉપયોગી આરોગ્યસેવા પહોંચાડવાના પ્રયાસો.",
    icon: "heart",
  },
  {
    id: "gurukul",
    titleGu: "ગુરુકુળ અને સંસ્કાર",
    kickerGu: "વૈદિક પરંપરા, નવી પેઢી",
    descriptionGu: "બાળ અને યુવા પેઢીમાં સંસ્કાર, શિસ્ત, આધ્યાત્મિક સમજ અને ભારતીય જ્ઞાનપરંપરાનો સ્નેહભર્યો પરિચય.",
    icon: "book",
  },
  {
    id: "sadavrat",
    titleGu: "અન્નક્ષેત્ર અને સમૂહ ભિક્ષા",
    kickerGu: "અન્નમાં અન્નપૂર્ણાનો ભાવ",
    descriptionGu: "સાધુ-સંત, યાત્રાળુ અને પ્રસંગોપાત ભક્તવૃંદ માટે અન્નસેવા અને સમૂહ ભિક્ષાની પરંપરા.",
    icon: "utensils",
  },
  {
    id: "environment",
    titleGu: "વૃક્ષારોપણ અને પર્યાવરણ",
    kickerGu: "પ્રકૃતિ પ્રત્યે કૃતજ્ઞતા",
    descriptionGu: "પર્યાવરણ જાગૃતિ, વૃક્ષારોપણ અને સ્વચ્છતા દ્વારા સેવા અને જવાબદારીને દૈનિક જીવન સાથે જોડવાનો પ્રયાસ.",
    icon: "sprout",
  },
  {
    id: "mandal",
    titleGu: "સેવક અને યુવક મંડળ",
    kickerGu: "સાથે મળીને સેવા",
    descriptionGu: "સ્થાનિક મંડળો દ્વારા કાર્યક્રમ વ્યવસ્થા, સેવા, યુવા પ્રવૃત્તિ અને ભક્તિપૂર્ણ સામૂહિક જોડાણ.",
    icon: "users",
  },
];

export const principles = [
  { title: "ધર્મ", line: "આચરણમાં સત્ય અને કર્તવ્ય" },
  { title: "ભક્તિ", line: "હૃદયમાં શ્રદ્ધા અને સમર્પણ" },
  { title: "જ્ઞાન", line: "વેદાંતથી આંતરિક પ્રકાશ" },
  { title: "વૈરાગ્ય", line: "સાદગી, સમતા અને સ્વાધ્યાય" },
];
