import { MailPlus, UserCog, Users } from "lucide-react";
import { assignAdminRoleAction, setAdminStatusAction } from "@/app/admin/actions";
import { inviteAdminAction } from "@/app/admin/team-actions";
import { getAdminAssignments, getAdminProfiles, getRoles, requireAdminSession } from "@/lib/admin/data";
import { getAdminAccessToken, supabaseRest } from "@/lib/supabase/server";

type Invitation={id:string;email:string;display_name:string;status:string;expires_at:string;scope_type:string;scope_key:string|null};
export default async function AdminTeamPage(){
 const session=await requireAdminSession();
 const [admins,roles,assignments]=await Promise.all([getAdminProfiles(session),getRoles(session),getAdminAssignments(session)]);
 const token=await getAdminAccessToken();
 const invitations=session.profile?.is_super_admin&&token?await supabaseRest<Invitation[]>("admin_invitations?select=*&order=created_at.desc&limit=30",token).catch(()=>[]):[];
 const roleName=new Map(roles.map(r=>[r.id,r.name_gu]));
 return <div><p className="text-xs font-bold text-gold-deep">COMMITTEE TEAM</p><h1 className="mt-1 font-serif text-2xl font-bold text-primary sm:text-3xl">એડમિન ટીમ</h1><p className="mt-1 text-sm text-muted-foreground">મુખ્ય એડમિન સહિત વધુમાં વધુ ૧૦ સક્રિય એડમિન. દરેકને કામ પ્રમાણે role અને scope આપો.</p>
 {session.profile?.is_super_admin?<section className="mt-5 rounded-2xl border border-[#ded6ca] bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><MailPlus className="size-5 text-primary"/><h2 className="font-bold">નવો એડમિન આમંત્રિત કરો</h2></div><form action={inviteAdminAction} className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><input className="field" name="display_name" placeholder="નામ" required/><input className="field" type="email" name="email" placeholder="ઇમેઇલ" required/><select className="field" name="role_id"><option value="">Role પછી આપશો</option>{roles.map(r=><option value={r.id} key={r.id}>{r.name_gu}</option>)}</select><select className="field" name="scope_type"><option value="global">Global</option><option value="ashram">Ashram</option><option value="module">Module</option></select><div className="flex gap-2"><input className="field min-w-0" name="scope_key" placeholder="Scope optional"/><button className="min-h-11 shrink-0 rounded-xl bg-primary px-4 text-sm font-bold text-white">Invite</button></div></form><p className="mt-3 text-xs leading-5 text-muted-foreground">Supabase સુરક્ષિત invitation email મોકલે છે. આમંત્રિત વ્યક્તિ password સેટ કર્યા પછી અહીંથી Activate કરી શકાય છે.</p>{invitations.length?<div className="mt-4 grid gap-2 sm:grid-cols-2">{invitations.slice(0,6).map(i=><div className="rounded-xl bg-[#f8f5f0] p-3 text-xs" key={i.id}><div className="font-bold">{i.display_name}</div><div className="mt-1 truncate text-muted-foreground">{i.email}</div><span className="mt-2 inline-block rounded-full bg-white px-2 py-1 font-bold">{i.status}</span></div>)}</div>:null}</section>:null}
 <div className="mt-5 space-y-3">{admins.map(admin=>{const assigned=assignments.filter(x=>x.admin_id===admin.id);return <article key={admin.id} className="rounded-2xl border border-[#dfd9d0] bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-full bg-[#f0e6dc] font-bold text-primary">{admin.display_name.charAt(0)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{admin.display_name}</h2>{admin.is_super_admin?<span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-bold text-white">SUPER ADMIN</span>:null}<span className="rounded-full bg-[#f5f1eb] px-2 py-0.5 text-[10px] font-bold">{admin.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{assigned.length?assigned.map(x=>`${roleName.get(x.role_id)??x.role_id}${x.scope_type!=="global"?` (${x.scope_key??x.scope_type})`:""}`).join(" • "):"હજુ કોઈ role નથી"}</p></div><Users className="size-5 text-[#ae9d8d]"/></div>{session.profile?.is_super_admin&&!admin.is_super_admin?<div className="mt-4 grid gap-2 border-t border-[#eee9e2] pt-3 sm:grid-cols-[1fr_auto]"><form action={assignAdminRoleAction} className="grid gap-2 sm:grid-cols-[1fr_130px_1fr_auto]"><input type="hidden" name="admin_id" value={admin.id}/><select name="role_id" className="field !min-h-10 text-xs" required><option value="">Role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name_gu}</option>)}</select><select name="scope_type" className="field !min-h-10 text-xs"><option value="global">Global</option><option value="ashram">Ashram</option><option value="module">Module</option></select><input name="scope_key" className="field !min-h-10 text-xs" placeholder="Scope optional"/><button className="rounded-xl bg-[#eee7de] px-3 text-xs font-bold text-primary">Role આપો</button></form><form action={setAdminStatusAction}><input type="hidden" name="admin_id" value={admin.id}/><input type="hidden" name="status" value={admin.status==="active"?"suspended":"active"}/><button className="flex min-h-10 items-center gap-1.5 rounded-xl border px-3 text-xs font-bold"><UserCog className="size-3.5"/>{admin.status==="active"?"Suspend":"Activate"}</button></form></div>:null}</article>})}</div></div>;
}
