"use client";
import { useState } from "react";
import { Minus, Plus, Utensils } from "lucide-react";
import { submitStayRequestAction } from "@/app/(site)/stay/actions";
import type { PublicAshram } from "@/lib/operations/public-data";

export function StayRequestForm({ashrams}:{ashrams:PublicAshram[]}){
  const [guestCount,setGuestCount]=useState(0);const [meals,setMeals]=useState(false);const total=guestCount+1;
  return <form action={submitStayRequestAction} className="space-y-5"><input name="website" className="hidden" tabIndex={-1}/><input type="hidden" name="guest_count" value={guestCount}/><section className="rounded-3xl border border-border bg-white p-5 shadow-sm sm:p-7"><h2 className="font-serif text-2xl font-bold text-primary">૧. મુખ્ય અરજદાર અને રહેવાની તારીખ</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold">નામ *<input className="field" name="applicant_name" required/></label><label className="grid gap-1.5 text-sm font-semibold">મોબાઇલ નંબર *<input className="field" name="mobile" type="tel" required/></label><label className="grid gap-1.5 text-sm font-semibold">ગામ / મૂળ વતન *<input className="field" name="native_village" required/></label><label className="grid gap-1.5 text-sm font-semibold">રેફરન્સ<input className="field" name="reference_name"/></label><label className="grid gap-1.5 text-sm font-semibold">આશ્રમ *<select className="field" name="ashram_id" required><option value="">પસંદ કરો</option>{ashrams.map(a=><option key={a.id} value={a.id}>{a.name_gu}</option>)}</select></label><span/><label className="grid gap-1.5 text-sm font-semibold">તારીખથી *<input className="field" name="check_in" type="date" required/></label><label className="grid gap-1.5 text-sm font-semibold">તારીખ સુધી *<input className="field" name="check_out" type="date" required/></label><label className="grid gap-1.5 text-sm font-semibold sm:col-span-2">પૂર્ણ એડ્રેસ *<textarea className="field min-h-24" name="full_address" required/></label></div></section>
  <section className="rounded-3xl border border-border bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="font-serif text-2xl font-bold text-primary">૨. કુલ સભ્યો</h2><p className="mt-1 text-sm text-muted-foreground">મુખ્ય અરજદાર સહિત કુલ {total} સભ્ય.</p></div><div className="flex items-center gap-2"><button type="button" onClick={()=>setGuestCount(v=>Math.max(0,v-1))} className="grid size-11 place-items-center rounded-full border border-border"><Minus className="size-4"/></button><span className="min-w-10 text-center text-xl font-bold">{guestCount}</span><button type="button" onClick={()=>setGuestCount(v=>Math.min(19,v+1))} className="grid size-11 place-items-center rounded-full bg-primary text-white"><Plus className="size-4"/></button></div></div><p className="mt-2 text-xs text-muted-foreground">ઉપરની સંખ્યા મુખ્ય અરજદાર સિવાય સાથે આવનાર સભ્યોની છે.</p><div className="mt-4 space-y-3">{Array.from({length:guestCount},(_,i)=><div key={i} className="grid gap-3 rounded-2xl bg-surface-soft p-4 sm:grid-cols-[1fr_110px_160px]"><label className="grid gap-1 text-xs font-bold">સભ્ય {i+2} નામ *<input className="field" name={`guest_${i}_full_name`} required/></label><label className="grid gap-1 text-xs font-bold">ઉંમર<input className="field" name={`guest_${i}_age`} type="number" min={0} max={120}/></label><label className="grid gap-1 text-xs font-bold">સંબંધ<input className="field" name={`guest_${i}_relationship`}/></label></div>)}</div></section>
  <section className="rounded-3xl border border-border bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><Utensils className="size-5 text-gold-deep"/><h2 className="font-serif text-2xl font-bold text-primary">૩. પ્રસાદ / ભોજન</h2></div><label className="mt-4 flex min-h-12 items-center gap-3 rounded-xl bg-surface-soft px-4 font-semibold"><input type="checkbox" name="takes_prasad" value="yes" checked={meals} onChange={e=>setMeals(e.target.checked)}/>આશ્રમમાં પ્રસાદ / ભોજન લેવાના છે</label>{meals?<div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm font-semibold">નાસ્તો સંખ્યા<input className="field" name="breakfast_count" type="number" min={0} max={total} defaultValue={total}/></label><label className="grid gap-1 text-sm font-semibold">બપોરનું ભોજન<input className="field" name="lunch_count" type="number" min={0} max={total} defaultValue={total}/></label><label className="grid gap-1 text-sm font-semibold">રાત્રિ ભોજન<input className="field" name="dinner_count" type="number" min={0} max={total} defaultValue={total}/></label></div>:null}</section>
  <div className="rounded-2xl border border-[#dccfbf] bg-[#fff8ec] p-4 text-sm leading-7 text-muted-foreground"><strong className="text-primary">આધાર દસ્તાવેજ:</strong> અરજીની તારીખ અને રૂમ ઉપલબ્ધતા તપાસ્યા પછી સમિતિ “Documents Required” સ્થિતિમાં સુરક્ષિત અપલોડ કડી આપશે. ઓળખપત્રો જાહેર મીડિયા સાથે ક્યારેય રાખવામાં નહીં આવે.</div><button className="min-h-13 w-full rounded-xl bg-primary px-6 py-3.5 font-bold text-white">રૂમ / ઉતારા માટે વિનંતી મોકલો</button></form>;
}
