import type { Metadata } from "next";
import { CalendarDays, ExternalLink, FileText, MapPin, Users } from "lucide-react";

import { getPublicProgrammeCentres, getPublicProgrammeCirculars, getPublicTithiProgrammes } from "@/lib/operations/public-data";

export const metadata: Metadata = { title: "સત્સંગ, બાળ શિબિર અને કાર્યક્રમો", description: "સત્સંગ કેન્દ્રો, બાળ શિબિર, વર્તમાન કાર્યક્રમ પરિપત્ર અને તિથિ કાર્યક્રમોની એકીકૃત માહિતી." };

const kindLabel:Record<string,string>={satsang:"સત્સંગ",bal_shibir:"બાળ શિબિર",both:"સત્સંગ + બાળ શિબિર",tithi:"તિથિ",special:"વિશેષ",tour:"સ્વામીજી કાર્યક્રમ",poonam:"પૂનમ ઉત્સવ"};

export default async function ProgrammesPage(){
  const [centres,circulars,tithis]=await Promise.all([getPublicProgrammeCentres(),getPublicProgrammeCirculars(),getPublicTithiProgrammes()]);
  return <>
    <section className="border-b border-border bg-[#f4eee5]"><div className="container-site py-12 sm:py-16"><div className="max-w-4xl"><div className="eyebrow">સત્સંગ અને બાળ શિબિર</div><h1 className="display-title mt-4 text-primary">એક જ જગ્યાએ કેન્દ્રો, પરિપત્ર અને આગામી કાર્યક્રમો</h1><p className="body-large mt-5">સમિતિ દ્વારા પ્રકાશિત થયેલી માહિતી અહીં દેખાય છે. સરનામું, સમય અને મેપ કડી કાર્યક્રમ પ્રમાણે અપડેટ થઈ શકે છે.</p></div></div></section>

    <section className="section-pad"><div className="container-site"><div className="flex items-center gap-2"><FileText className="size-5 text-gold-deep"/><h2 className="font-serif text-3xl font-bold text-primary">Current Programme / Circular</h2></div><div className="mt-6 grid gap-4 md:grid-cols-2">{circulars.length?circulars.map(item=><article key={item.id} className="card-sacred p-5"><p className="text-xs font-bold text-gold-deep">{kindLabel[item.category]??item.category}</p><h3 className="mt-2 font-serif text-xl font-bold text-primary">{item.title_gu}</h3>{item.description_gu?<p className="mt-2 text-sm leading-7 text-muted-foreground">{item.description_gu}</p>:null}<div className="mt-4 flex flex-wrap gap-2">{item.pdf_url?<a className="inline-flex min-h-11 items-center gap-2 rounded-full bg-primary px-4 text-sm font-bold text-white" href={item.pdf_url} target="_blank" rel="noreferrer">PDF <ExternalLink className="size-4"/></a>:null}{item.image_url?<a className="inline-flex min-h-11 items-center gap-2 rounded-full border border-primary/25 px-4 text-sm font-bold text-primary" href={item.image_url} target="_blank" rel="noreferrer">કાર્ડ જુઓ</a>:null}</div></article>):<div className="rounded-2xl border border-dashed border-border p-7 text-sm text-muted-foreground md:col-span-2">હાલ કોઈ નવો અધિકૃત પરિપત્ર પ્રકાશિત નથી.</div>}</div></div></section>

    <section className="border-y border-border bg-surface section-pad"><div className="container-site"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-primary"/><h2 className="font-serif text-3xl font-bold text-primary">આગામી તિથિ અને કાર્યક્રમો</h2></div><div className="mt-6 overflow-hidden rounded-2xl border border-border bg-background">{tithis.length?tithis.map(item=><article key={item.id} className="grid gap-3 border-b border-border p-4 last:border-0 md:grid-cols-[150px_1fr_auto] md:items-center"><div><p className="font-bold text-primary">{item.programme_date}</p><p className="text-xs text-muted-foreground">{item.weekday_gu||""} {item.tithi_name_gu?`• ${item.tithi_name_gu}`:""}</p></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{item.title_gu}</h3><span className="rounded-full bg-[#f3eee7] px-2 py-0.5 text-[10px] font-bold">{kindLabel[item.programme_type]??item.programme_type}</span></div><p className="mt-1 text-sm text-muted-foreground">{item.swamiji_name?`${item.swamiji_name} • `:""}{item.village_city_gu}{item.venue_gu?` • ${item.venue_gu}`:""}</p></div>{item.map_url?<a href={item.map_url} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 text-sm font-bold text-primary"><MapPin className="size-4"/>મેપ</a>:null}</article>):<p className="p-7 text-sm text-muted-foreground">હાલ કોઈ આગામી કાર્યક્રમ પ્રકાશિત નથી.</p>}</div></div></section>

    <section className="section-pad"><div className="container-site"><div className="flex items-center gap-2"><Users className="size-5 text-sacred-green"/><h2 className="font-serif text-3xl font-bold text-primary">સત્સંગ અને બાળ શિબિર કેન્દ્રો</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{centres.length?centres.map(item=><article key={item.id} className="card-sacred p-5"><p className="text-xs font-bold text-sacred-green">{kindLabel[item.kind]??item.kind}</p><h3 className="mt-2 font-serif text-xl font-bold text-primary">{item.title_gu}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{item.address_gu}<br/>{item.city_gu}</p>{item.schedule_text?<p className="mt-3 rounded-xl bg-surface-soft p-3 text-sm font-semibold">{item.schedule_text}</p>:null}<div className="mt-4 flex flex-wrap gap-3 text-sm font-bold text-primary">{item.contact_mobile?<a href={`tel:${item.contact_mobile}`}>{item.contact_mobile}</a>:null}{item.map_url?<a href={item.map_url} target="_blank" rel="noreferrer">મેપ ↗</a>:null}</div></article>):<div className="rounded-2xl border border-dashed border-border p-7 text-sm text-muted-foreground sm:col-span-2 lg:col-span-3">કેન્દ્રોની યાદી સમિતિ દ્વારા ઉમેરાયા પછી અહીં દેખાશે.</div>}</div></div></section>
  </>;
}
