import Link from "next/link";
import { ArrowRight, BedDouble, Building2 } from "lucide-react";
import { getAdminAshrams,getStayRequests } from "@/lib/operations/admin-data";
import { hasAdminPermission,requireAdminSession } from "@/lib/admin/data";
import { saveAshramProfileAction } from "@/app/admin/operations/actions";
export default async function AdminStaysPage(){const s=await requireAdminSession();const[requests,ashrams]=await Promise.all([getStayRequests(s),getAdminAshrams(s)]);const manage=hasAdminPermission(s,"ashrams.manage");return <div><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold text-gold-deep">ASHRAM STAYS</p><h1 className="mt-1 font-serif text-2xl font-bold text-primary sm:text-3xl">ઉતારા અને રૂમ વ્યવસ્થા</h1><p className="mt-1 text-sm text-muted-foreground">અરજી → તપાસ → દસ્તાવેજ → મંજૂરી → રૂમ ફાળવણી → ચેક-આઉટ.</p></div><Link href="/admin/stays/rooms" className="min-h-11 rounded-xl bg-primary px-4 py-3 text-xs font-bold text-white">રૂમો</Link></div>
{manage?<details className="mt-5 rounded-2xl border border-border bg-white p-4"><summary className="cursor-pointer font-bold text-primary">+ આશ્રમ પ્રોફાઇલ / રહેવાની સુવિધા</summary><form action={saveAshramProfileAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input className="field" name="slug" placeholder="slug" required/><input className="field" name="name_gu" placeholder="આશ્રમ નામ" required/><input className="field" name="city_gu" placeholder="શહેર" required/><input className="field" name="state_gu" placeholder="રાજ્ય"/><textarea className="field min-h-20 sm:col-span-2" name="full_address" placeholder="ચકાસેલું એડ્રેસ"/><input className="field" name="office_phone" placeholder="ઓફિસ ફોન"/><input className="field" name="manager_name" placeholder="મેનેજર નામ (આંતરિક/ચકાસેલું)"/><input className="field" name="manager_mobile" placeholder="મેનેજર મોબાઇલ"/><input className="field" name="map_url" placeholder="Map URL"/><textarea className="field min-h-24 sm:col-span-2" name="rules_md" placeholder="આશ્રમ રહેવાના નિયમો"/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="accepts_stays"/> રહેવાની અરજી લેવી</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="published"/> જાહેર યાદીમાં</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="verified"/> વિગતો ચકાસેલી</label><button className="min-h-11 rounded-xl bg-primary text-white font-bold">સાચવો</button></form></details>:null}
<section className="mt-7"><div className="flex items-center gap-2"><Building2 className="size-5 text-primary"/><h2 className="font-serif text-xl font-bold text-primary">રહેવાની સુવિધાવાળા આશ્રમ</h2></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ashrams.filter(a=>a.accepts_stays).map(a=><div key={a.id} className="rounded-2xl border border-border bg-white p-4"><p className="font-bold">{a.name_gu}</p><p className="mt-1 text-xs text-muted-foreground">{a.city_gu} • {a.verified?"ચકાસેલું":"ચકાસણી બાકી"}</p></div>)}</div></section>
<section className="mt-7"><div className="flex items-center gap-2"><BedDouble className="size-5 text-sacred-green"/><h2 className="font-serif text-xl font-bold text-primary">રૂમ અરજીઓ ({requests.length})</h2></div><div className="mt-3 space-y-3">{requests.map(r=><Link href={`/admin/stays/${r.id}`} key={r.id} className="flex min-h-20 items-center gap-3 rounded-2xl border border-border bg-white p-4"><div className="min-w-0 flex-1"><p className="font-bold">{r.applicant_name}</p><p className="mt-1 text-xs text-muted-foreground">{r.request_number} • {r.check_in} → {r.check_out} • {r.total_members} સભ્ય • {r.status}</p></div><ArrowRight className="size-4 text-muted-foreground"/></Link>)}</div></section></div>}
