import { PlusCircle } from "lucide-react";

import { createInboxItemAction } from "@/app/admin/actions";
import { hasAdminPermission, requireAdminSession } from "@/lib/admin/data";

export default async function AdminQuickAddPage() {
  const session = await requireAdminSession();
  const allowed = hasAdminPermission(session, "inbox.update");
  return <div><p className="text-xs font-bold text-gold-deep">QUICK ADD</p><h1 className="mt-1 font-serif text-2xl font-bold text-primary sm:text-3xl">ઝડપી નોંધ ઉમેરો</h1><p className="mt-1 text-sm text-muted-foreground">ફોન/ઓફિસથી આવેલી વિનંતી તરત ઇનબોક્સમાં ઉમેરો.</p>{allowed ? <form action={createInboxItemAction} className="mt-5 grid gap-4 rounded-2xl border border-[#dfd9d0] bg-white p-4 shadow-sm sm:grid-cols-2 sm:p-5"><label className="sm:col-span-2 text-sm font-bold">શીર્ષક<input name="title" className="field mt-2" required placeholder="ઉદાહરણ: ચાણોદ રૂમ વિશે ફોન" /></label><label className="text-sm font-bold">પ્રકાર<select name="category" className="field mt-2"><option value="manual">આંતરિક નોંધ</option><option value="room_booking">રૂમ બુકિંગ</option><option value="membership">સભ્યપદ</option><option value="volunteer">સ્વયંસેવક</option><option value="veda_rahasya">વેદ રહસ્ય</option><option value="inquiry">પૂછપરછ</option></select></label><label className="text-sm font-bold">પ્રાથમિકતા<select name="priority" className="field mt-2"><option value="normal">સામાન્ય</option><option value="high">પ્રાથમિક</option><option value="urgent">તાત્કાલિક</option></select></label><label className="text-sm font-bold">નામ<input name="contact_name" className="field mt-2" /></label><label className="text-sm font-bold">મોબાઇલ<input name="contact_mobile" className="field mt-2" inputMode="tel" /></label><label className="text-sm font-bold">આશ્રમ<input name="ashram_key" className="field mt-2" placeholder="Surat / Chanod..." /></label><label className="text-sm font-bold">ટૂંકી વિગત<input name="subtitle" className="field mt-2" /></label><button className="sm:col-span-2 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary font-bold text-white" type="submit"><PlusCircle className="size-4" /> ઇનબોક્સમાં ઉમેરો</button></form> : <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm font-semibold text-amber-900">આ ભૂમિકા પાસે નવી નોંધ ઉમેરવાની પરવાનગી નથી.</p>}</div>;
}
