import { Archive, CalendarDays, FileText, MapPin, Radio, RotateCcw, Trash2 } from "lucide-react";
import {
  archiveCircularAction,
  archiveProgrammeCentreAction,
  permanentDeleteAction,
  restoreCircularAction,
  restoreProgrammeCentreAction,
  saveCircularAction,
  saveProgrammeCentreAction,
  saveTithiAction,
  setTithiStatusAction,
} from "@/app/admin/operations/actions";
import { getAdminAshrams,getProgrammeCentres,getProgrammeCirculars,getTithiProgrammes } from "@/lib/operations/admin-data";
import { hasAdminPermission,requireAdminSession } from "@/lib/admin/data";

type Ashram = Awaited<ReturnType<typeof getAdminAshrams>>[number];
type Centre = Awaited<ReturnType<typeof getProgrammeCentres>>[number];
type Circular = Awaited<ReturnType<typeof getProgrammeCirculars>>[number];
type Tithi = Awaited<ReturnType<typeof getTithiProgrammes>>[number];

function CentreForm({ashrams,item,publish}:{ashrams:Ashram[];item?:Centre;publish:boolean}){return <form action={saveProgrammeCentreAction} className="mt-4 grid gap-3 sm:grid-cols-2">{item?<input type="hidden" name="id" value={item.id}/>:null}<select className="field" name="kind" defaultValue={item?.kind??"satsang"}><option value="satsang">સત્સંગ</option><option value="bal_shibir">બાળ શિબિર</option><option value="both">બંને</option></select><input className="field" name="title_gu" placeholder="કેન્દ્રનું નામ" defaultValue={item?.title_gu??""} required/><input className="field" name="address_gu" placeholder="એડ્રેસ" defaultValue={item?.address_gu??""} required/><input className="field" name="city_gu" placeholder="શહેર" defaultValue={item?.city_gu??""} required/><select className="field" name="ashram_id" defaultValue={item?.ashram_id??""}><option value="">આશ્રમ જોડાણ (વૈકલ્પિક)</option>{ashrams.map(a=><option value={a.id} key={a.id}>{a.name_gu}</option>)}</select><input className="field" name="schedule_text" placeholder="સમય / દિવસ" defaultValue={item?.schedule_text??""}/><input className="field" name="contact_name" placeholder="સંપર્ક વ્યક્તિ" defaultValue={item?.contact_name??""}/><input className="field" name="contact_mobile" placeholder="સંપર્ક નંબર" defaultValue={item?.contact_mobile??""}/><input className="field" name="map_url" placeholder="Google Map URL" defaultValue={item?.map_url??""}/><input className="field" name="age_range_text" placeholder="ઉંમર મર્યાદા" defaultValue={item?.age_range_text??""}/><textarea className="field min-h-20 sm:col-span-2" name="notes" placeholder="નોંધ" defaultValue={item?.notes??""}/><input className="field" name="sort_order" type="number" defaultValue={item?.sort_order??100}/>{publish?<label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="published" defaultChecked={item?.published??false}/> પ્રકાશિત</label>:null}<button className="min-h-11 rounded-xl bg-primary px-4 font-bold text-white">{item?"ફેરફાર સાચવો":"સાચવો"}</button></form>}

function CircularForm({item,publish}:{item?:Circular;publish:boolean}){return <form action={saveCircularAction} className="mt-4 grid gap-3 sm:grid-cols-2">{item?<input type="hidden" name="id" value={item.id}/>:null}<input className="field" name="title_gu" placeholder="શીર્ષક" defaultValue={item?.title_gu??""} required/><select className="field" name="category" defaultValue={item?.category??"current_programme"}><option value="current_programme">Current Programme</option><option value="tour">Swamiji Tour</option><option value="bal_shibir">બાળ શિબિર</option><option value="satsang">સત્સંગ</option><option value="notice">સૂચના</option></select><textarea className="field min-h-20 sm:col-span-2" name="description_gu" placeholder="વિગત" defaultValue={item?.description_gu??""}/><input className="field" name="image_url" placeholder="Image URL" defaultValue={item?.image_url??""}/><input className="field" name="pdf_url" placeholder="PDF URL" defaultValue={item?.pdf_url??""}/><input className="field" name="valid_from" type="date" defaultValue={item?.valid_from??""}/><input className="field" name="valid_until" type="date" defaultValue={item?.valid_until??""}/>{publish?<label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="published" defaultChecked={item?.published??false}/> પ્રકાશિત</label>:null}<button className="min-h-11 rounded-xl bg-primary px-4 font-bold text-white">{item?"ફેરફાર સાચવો":"સાચવો"}</button></form>}

function TithiForm({ashrams,item,eventPublish}:{ashrams:Ashram[];item?:Tithi;eventPublish:boolean}){return <form action={saveTithiAction} className="mt-4 grid gap-3 sm:grid-cols-2">{item?<input type="hidden" name="id" value={item.id}/>:null}<input className="field" name="title_gu" placeholder="કાર્યક્રમ શીર્ષક" defaultValue={item?.title_gu??""} required/><select className="field" name="programme_type" defaultValue={item?.programme_type??"tithi"}><option value="tithi">તિથિ</option><option value="satsang">સત્સંગ</option><option value="bal_shibir">બાળ શિબિર</option><option value="special">વિશેષ</option><option value="tour">Swamiji કાર્યક્રમ</option><option value="poonam">પૂનમ</option></select><input className="field" name="programme_date" type="date" defaultValue={item?.programme_date??""} required/><input className="field" name="weekday_gu" placeholder="વાર" defaultValue={item?.weekday_gu??""}/><input className="field" name="tithi_name_gu" placeholder="તિથિ નામ" defaultValue={item?.tithi_name_gu??""}/><input className="field" name="tithi_number" placeholder="તિથિ નંબર" defaultValue={item?.tithi_number??""}/><input className="field" name="swamiji_name" placeholder="Swamiji નું નામ" defaultValue={item?.swamiji_name??""}/><input className="field" name="village_city_gu" placeholder="ગામ / શહેર" defaultValue={item?.village_city_gu??""} required/><input className="field" name="venue_gu" placeholder="સ્થળ" defaultValue={item?.venue_gu??""}/><input className="field" name="map_url" placeholder="Map URL" defaultValue={item?.map_url??""}/><input className="field" name="image_url" placeholder="Photo URL" defaultValue={item?.image_url??""}/><input className="field" name="pdf_url" placeholder="PDF URL" defaultValue={item?.pdf_url??""}/><select className="field" name="ashram_id" defaultValue={item?.ashram_id??""}><option value="">આશ્રમ</option>{ashrams.map(a=><option key={a.id} value={a.id}>{a.name_gu}</option>)}</select><select className="field" name="status" defaultValue={item?.status==="archived"?"draft":item?.status??"draft"}><option value="draft">ડ્રાફ્ટ</option>{eventPublish?<option value="published">પ્રકાશિત</option>:null}</select><textarea className="field min-h-24 sm:col-span-2" name="details_gu" placeholder="કાર્યક્રમની વિગત" defaultValue={item?.details_gu??""}/><button className="min-h-11 rounded-xl bg-primary px-4 font-bold text-white">{item?"ફેરફાર સાચવો":"સાચવો"}</button></form>}

export default async function AdminProgrammesPage(){
  const s=await requireAdminSession();
  const[ashrams,centres,circulars,tithis]=await Promise.all([getAdminAshrams(s),getProgrammeCentres(s),getProgrammeCirculars(s),getTithiProgrammes(s)]);
  const manage=hasAdminPermission(s,"programmes.manage"),publish=hasAdminPermission(s,"programmes.publish"),events=hasAdminPermission(s,"events.manage"),eventPublish=hasAdminPermission(s,"events.publish"),superAdmin=Boolean(s.profile?.is_super_admin);
  return <div><p className="text-xs font-bold text-gold-deep">PROGRAMMES</p><h1 className="mt-1 font-serif text-2xl font-bold text-primary sm:text-3xl">સત્સંગ, બાળ શિબિર અને કાર્યક્રમો</h1><p className="mt-1 text-sm text-muted-foreground">અહીંના પ્રકાશિત રેકોર્ડ જ જાહેર Programmes/Events પાનાં પર દેખાય છે. Draft અને Archived રેકોર્ડ જાહેરમાં દેખાતા નથી.</p>

  {manage?<details className="mt-5 rounded-2xl border border-border bg-white p-4"><summary className="cursor-pointer font-bold text-primary">+ નવું સત્સંગ / બાળ શિબિર કેન્દ્ર</summary><CentreForm ashrams={ashrams} publish={publish}/></details>:null}
  <section className="mt-7"><div className="flex items-center gap-2"><Radio className="size-5 text-primary"/><h2 className="font-serif text-xl font-bold text-primary">કેન્દ્રો ({centres.length})</h2></div><div className="mt-3 grid gap-3 md:grid-cols-2">{centres.map(c=><article key={c.id} className={`rounded-2xl border bg-white p-4 ${c.archived_at?"border-dashed opacity-70":"border-border"}`}><p className="font-bold">{c.title_gu}</p><p className="mt-1 text-xs text-muted-foreground">{c.city_gu} • {c.kind} • {c.archived_at?"Archived":c.published?"પ્રકાશિત":"Draft"}</p>{manage&&!c.archived_at?<details className="mt-3 rounded-xl bg-[#f8f4ee] p-3"><summary className="cursor-pointer text-sm font-bold text-primary">Edit</summary><CentreForm ashrams={ashrams} item={c} publish={publish}/></details>:null}{manage?<div className="mt-3 flex flex-wrap gap-2">{c.archived_at?<form action={restoreProgrammeCentreAction}><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold"><RotateCcw className="size-4"/>Restore</button></form>:<form action={archiveProgrammeCentreAction}><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold text-muted-foreground"><Archive className="size-4"/>Archive</button></form>}{superAdmin?<form action={permanentDeleteAction}><input type="hidden" name="table" value="programme_centres"/><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-red-200 px-3 text-sm font-bold text-red-700"><Trash2 className="size-4"/>Delete</button></form>:null}</div>:null}</article>)}</div></section>

  {manage?<details className="mt-7 rounded-2xl border border-border bg-white p-4"><summary className="cursor-pointer font-bold text-primary">+ Current Programme / Circular</summary><CircularForm publish={publish}/></details>:null}
  <section className="mt-7"><div className="flex items-center gap-2"><FileText className="size-5 text-gold-deep"/><h2 className="font-serif text-xl font-bold text-primary">પરિપત્રો ({circulars.length})</h2></div><div className="mt-3 space-y-3">{circulars.map(c=><article key={c.id} className={`rounded-2xl border bg-white p-4 ${c.archived_at?"border-dashed opacity-70":"border-border"}`}><p className="font-bold">{c.title_gu}</p><p className="text-xs text-muted-foreground">{c.category} • {c.archived_at?"Archived":c.published?"પ્રકાશિત":"Draft"}</p>{manage&&!c.archived_at?<details className="mt-3 rounded-xl bg-[#f8f4ee] p-3"><summary className="cursor-pointer text-sm font-bold text-primary">Edit</summary><CircularForm item={c} publish={publish}/></details>:null}{manage?<div className="mt-3 flex flex-wrap gap-2">{c.archived_at?<form action={restoreCircularAction}><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold"><RotateCcw className="size-4"/>Restore</button></form>:<form action={archiveCircularAction}><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold text-muted-foreground"><Archive className="size-4"/>Archive</button></form>}{superAdmin?<form action={permanentDeleteAction}><input type="hidden" name="table" value="programme_circulars"/><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-red-200 px-3 text-sm font-bold text-red-700"><Trash2 className="size-4"/>Delete</button></form>:null}</div>:null}</article>)}</div></section>

  {events?<details className="mt-7 rounded-2xl border border-border bg-white p-4"><summary className="cursor-pointer font-bold text-primary">+ તિથિ / પૂનમ / Swamiji કાર્યક્રમ</summary><TithiForm ashrams={ashrams} eventPublish={eventPublish}/></details>:null}
  <section className="mt-7"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-sacred-green"/><h2 className="font-serif text-xl font-bold text-primary">તિથિ અને કાર્યક્રમો ({tithis.length})</h2></div><div className="mt-3 space-y-3">{tithis.map(t=><article key={t.id} className={`rounded-2xl border bg-white p-4 ${t.status==="archived"?"border-dashed opacity-70":"border-border"}`}><div className="grid gap-2 sm:grid-cols-[120px_1fr_auto]"><div className="font-bold text-primary">{t.programme_date}</div><div><p className="font-bold">{t.title_gu}</p><p className="text-xs text-muted-foreground">{t.village_city_gu} • {t.status}</p></div>{t.map_url?<a className="inline-flex items-center gap-1 text-xs font-bold text-primary" href={t.map_url} target="_blank" rel="noreferrer"><MapPin className="size-3.5"/>મેપ</a>:null}</div>{events&&t.status!=="archived"?<details className="mt-3 rounded-xl bg-[#f8f4ee] p-3"><summary className="cursor-pointer text-sm font-bold text-primary">Edit</summary><TithiForm ashrams={ashrams} item={t} eventPublish={eventPublish}/></details>:null}{events?<div className="mt-3 flex flex-wrap gap-2">{t.status==="archived"?<form action={setTithiStatusAction}><input type="hidden" name="id" value={t.id}/><input type="hidden" name="status" value="draft"/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold"><RotateCcw className="size-4"/>Restore to Draft</button></form>:<><form action={setTithiStatusAction}><input type="hidden" name="id" value={t.id}/><input type="hidden" name="status" value="draft"/><button className="min-h-10 rounded-xl border border-border px-3 text-sm font-bold">Draft</button></form>{eventPublish?<form action={setTithiStatusAction}><input type="hidden" name="id" value={t.id}/><input type="hidden" name="status" value="published"/><button className="min-h-10 rounded-xl bg-primary px-3 text-sm font-bold text-white">Publish</button></form>:null}<form action={setTithiStatusAction}><input type="hidden" name="id" value={t.id}/><input type="hidden" name="status" value="archived"/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold text-muted-foreground"><Archive className="size-4"/>Archive</button></form></>}{superAdmin?<form action={permanentDeleteAction}><input type="hidden" name="table" value="tithi_programmes"/><input type="hidden" name="id" value={t.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-red-200 px-3 text-sm font-bold text-red-700"><Trash2 className="size-4"/>Delete</button></form>:null}</div>:null}</article>)}</div></section>
  </div>;
}
