"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { hasAdminPermission, requireAdminSession } from "@/lib/admin/data";
import { getAdminAccessToken, supabaseRest } from "@/lib/supabase/server";

const str=(fd:FormData,n:string,max=6000)=>{const v=String(fd.get(n)??"").trim();return v?v.slice(0,max):null};
const bool=(fd:FormData,n:string)=>fd.get(n)==="on"||fd.get(n)==="true";
const num=(fd:FormData,n:string,def=100)=>{const v=Number(str(fd,n,10));return Number.isFinite(v)?v:def};
const permissions:Record<string,string>={guru_profiles:"guru.manage",guru_chapters:"guru.manage",heritage_documents:"heritage.manage",media_folders:"media.manage",media_assets:"media.manage"};
async function ctx(permission:string){const s=await requireAdminSession();if(!hasAdminPermission(s,permission)&&!s.profile?.is_super_admin)throw new Error("Permission denied");const token=await getAdminAccessToken();if(!token)redirect("/admin/login");return{s,token};}
async function upsert(table:string,id:string|null,record:Record<string,unknown>,token:string){if(id)await supabaseRest(`${table}?id=eq.${encodeURIComponent(id)}`,token,{method:"PATCH",body:JSON.stringify(record),prefer:"return=minimal"});else await supabaseRest(table,token,{method:"POST",body:JSON.stringify(record),prefer:"return=minimal"});}
const refresh=()=>{revalidatePath("/admin/heritage");revalidatePath("/admin/media");revalidatePath("/parampara");revalidatePath("/heritage");revalidatePath("/downloads");};

export async function saveGuruProfileAction(fd:FormData){const{s,token}=await ctx("guru.manage");const published=bool(fd,"published");if(published&&!hasAdminPermission(s,"guru.publish")&&!s.profile?.is_super_admin)throw new Error("Publish permission required");await upsert("guru_profiles",str(fd,"id",40),{slug:str(fd,"slug",120),name_gu:str(fd,"name_gu",240),source_title_en:str(fd,"source_title_en",300),qualification_gu:str(fd,"qualification_gu",160),portrait_url:str(fd,"portrait_url",1000),source_url:str(fd,"source_url",1000),source_status:str(fd,"source_status",120)??"committee-entered-review-required",lineage_order:str(fd,"lineage_order",10)?num(fd,"lineage_order"):null,featured:bool(fd,"featured"),published,archived_at:null},token);refresh();}
export async function saveGuruChapterAction(fd:FormData){const{s,token}=await ctx("guru.manage");const status=str(fd,"status",20)??"draft";if(status==="published"&&!hasAdminPermission(s,"guru.publish")&&!s.profile?.is_super_admin)throw new Error("Publish permission required");await upsert("guru_chapters",str(fd,"id",40),{guru_profile_id:str(fd,"guru_profile_id",40),slug:str(fd,"slug",120),title_gu:str(fd,"title_gu",240),summary_gu:str(fd,"summary_gu",1200),body_md:str(fd,"body_md",30000),sort_order:num(fd,"sort_order"),status,source_url:str(fd,"source_url",1000),review_required:bool(fd,"review_required"),updated_by:s.profile?.id??null},token);refresh();}
export async function saveHeritageDocumentAction(fd:FormData){const{s,token}=await ctx("heritage.manage");const status=str(fd,"status",20)??"draft";if(status==="published"&&!hasAdminPermission(s,"heritage.publish")&&!s.profile?.is_super_admin)throw new Error("Publish permission required");await upsert("heritage_documents",str(fd,"id",40),{kind:str(fd,"kind",40),title_gu:str(fd,"title_gu",240),description_gu:str(fd,"description_gu",3000),document_date:str(fd,"document_date",10),date_label_gu:str(fd,"date_label_gu",120),file_url:str(fd,"file_url",1000),image_url:str(fd,"image_url",1000),source_url:str(fd,"source_url",1000),status,sort_order:num(fd,"sort_order")},token);refresh();}
export async function saveMediaFolderAction(fd:FormData){const{s,token}=await ctx("media.manage");const published=bool(fd,"published");if(published&&!hasAdminPermission(s,"media.publish")&&!s.profile?.is_super_admin)throw new Error("Publish permission required");await upsert("media_folders",str(fd,"id",40),{parent_id:str(fd,"parent_id",40),slug:str(fd,"slug",120),title_gu:str(fd,"title_gu",240),category:str(fd,"category",30),description_gu:str(fd,"description_gu",1500),sort_order:num(fd,"sort_order"),published,archived_at:null},token);refresh();}
export async function saveMediaAssetAction(fd:FormData){const{s,token}=await ctx("media.manage");const published=bool(fd,"published");if(published&&!hasAdminPermission(s,"media.publish")&&!s.profile?.is_super_admin)throw new Error("Publish permission required");await upsert("media_assets",str(fd,"id",40),{folder_id:str(fd,"folder_id",40),title_gu:str(fd,"title_gu",240),media_type:str(fd,"media_type",30),asset_url:str(fd,"asset_url",1200),thumbnail_url:str(fd,"thumbnail_url",1200),mime_type:str(fd,"mime_type",120),duration_seconds:str(fd,"duration_seconds",10)?num(fd,"duration_seconds",0):null,source_url:str(fd,"source_url",1200),source_label:str(fd,"source_label",300),sort_order:num(fd,"sort_order"),published,archived_at:null},token);refresh();}

export async function archiveCmsRecordAction(fd:FormData){const table=str(fd,"table",80),id=str(fd,"id",40);if(!table||!id||!permissions[table])return;const{token}=await ctx(permissions[table]);const patch=table==="guru_chapters"||table==="heritage_documents"?{status:"archived"}:{archived_at:new Date().toISOString(),published:false};await supabaseRest(`${table}?id=eq.${encodeURIComponent(id)}`,token,{method:"PATCH",body:JSON.stringify(patch),prefer:"return=minimal"});refresh();}
export async function restoreCmsRecordAction(fd:FormData){const table=str(fd,"table",80),id=str(fd,"id",40);if(!table||!id||!permissions[table])return;const{token}=await ctx(permissions[table]);const patch=table==="guru_chapters"||table==="heritage_documents"?{status:"draft"}:{archived_at:null,published:false};await supabaseRest(`${table}?id=eq.${encodeURIComponent(id)}`,token,{method:"PATCH",body:JSON.stringify(patch),prefer:"return=minimal"});refresh();}
export async function permanentDeleteCmsRecordAction(fd:FormData){const s=await requireAdminSession();if(!s.profile?.is_super_admin)throw new Error("Super Admin required");const table=str(fd,"table",80),id=str(fd,"id",40);if(!table||!id||!permissions[table])return;const token=await getAdminAccessToken();if(!token)redirect("/admin/login");await supabaseRest(`${table}?id=eq.${encodeURIComponent(id)}`,token,{method:"DELETE",prefer:"return=minimal"});refresh();}
