import { Archive, HeartHandshake, RotateCcw, Trash2, UserCheck } from "lucide-react";
import { archiveOperationalRecordAction, permanentDeleteAction, restoreOperationalRecordAction, reviewVolunteerAction, saveSevaActivityAction, saveSevaCategoryAction } from "@/app/admin/operations/actions";
import { getAdminAshrams,getSevaActivities,getSevaCategories,getVolunteerApplications } from "@/lib/operations/admin-data";
import { hasAdminPermission,requireAdminSession } from "@/lib/admin/data";

type Category=Awaited<ReturnType<typeof getSevaCategories>>[number];
type Activity=Awaited<ReturnType<typeof getSevaActivities>>[number];
type Ashram=Awaited<ReturnType<typeof getAdminAshrams>>[number];

function CategoryForm({item}:{item?:Category}){return <form action={saveSevaCategoryAction} className="mt-4 grid gap-3">{item?<input type="hidden" name="id" value={item.id}/>:null}<input className="field" name="slug" placeholder="slug" defaultValue={item?.slug??""} required/><input className="field" name="title_gu" placeholder="ગુજરાતી નામ" defaultValue={item?.title_gu??""} required/><textarea className="field min-h-20" name="description_gu" placeholder="વિગત" defaultValue={item?.description_gu??""}/><input className="field" name="sort_order" type="number" defaultValue={item?.sort_order??100}/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="published" defaultChecked={item?.published??false}/> જાહેર વેબસાઇટ પર પ્રકાશિત</label><button className="min-h-11 rounded-xl bg-primary font-bold text-white">{item?"ફેરફાર સાચવો":"સાચવો"}</button></form>}

function ActivityForm({item,categories,ashrams}:{item?:Activity;categories:Category[];ashrams:Ashram[]}){return <form action={saveSevaActivityAction} className="mt-4 grid gap-3 sm:grid-cols-2">{item?<input type="hidden" name="id" value={item.id}/>:null}<select className="field" name="category_id" defaultValue={item?.category_id??""} required><option value="">ક્ષેત્ર</option>{categories.map(c=><option key={c.id} value={c.id}>{c.title_gu}</option>)}</select><input className="field" name="title_gu" placeholder="શીર્ષક" defaultValue={item?.title_gu??""} required/><textarea className="field min-h-20 sm:col-span-2" name="summary_gu" placeholder="ટૂંકી વિગત" defaultValue={item?.summary_gu??""}/><textarea className="field min-h-24 sm:col-span-2" name="details_gu" placeholder="વિગતવાર નોંધ" defaultValue={item?.details_gu??""}/><select className="field" name="ashram_id" defaultValue={item?.ashram_id??""}><option value="">આશ્રમ</option>{ashrams.map(a=><option key={a.id} value={a.id}>{a.name_gu}</option>)}</select><input className="field" name="activity_date" type="date" defaultValue={item?.activity_date??""}/><input className="field" name="metric_label_gu" placeholder="માપદંડ" defaultValue={item?.metric_label_gu??""}/><input className="field" name="metric_value" placeholder="મૂલ્ય" defaultValue={item?.metric_value??""}/><input className="field sm:col-span-2" name="cover_url" placeholder="Cover URL" defaultValue={item?.cover_url??""}/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="published" defaultChecked={item?.published??false}/> જાહેર વેબસાઇટ પર પ્રકાશિત</label><button className="min-h-11 rounded-xl bg-primary font-bold text-white">{item?"ફેરફાર સાચવો":"સાચવો"}</button></form>}

export default async function AdminSevaPage(){
  const s=await requireAdminSession();
  const[categories,activities,volunteers,ashrams]=await Promise.all([getSevaCategories(s),getSevaActivities(s),getVolunteerApplications(s),getAdminAshrams(s)]);
  const manage=hasAdminPermission(s,"seva.manage")||Boolean(s.profile?.is_super_admin),review=hasAdminPermission(s,"volunteer.review")||Boolean(s.profile?.is_super_admin),superAdmin=Boolean(s.profile?.is_super_admin);
  return <div><p className="text-xs font-bold text-gold-deep">SEVA & VOLUNTEERS</p><h1 className="mt-1 font-serif text-2xl font-bold text-primary sm:text-3xl">સેવા અને સ્વયંસેવક</h1><p className="mt-1 text-sm text-muted-foreground">પ્રકાશિત સેવા ક્ષેત્રો અને પ્રવૃત્તિઓ જ જાહેર `/seva` પાનાં અને homepage પર દેખાય છે.</p>

  {manage?<div className="mt-5 grid gap-3 lg:grid-cols-2"><details className="rounded-2xl border border-border bg-white p-4"><summary className="cursor-pointer font-bold text-primary">+ સેવા ક્ષેત્ર</summary><CategoryForm/></details><details className="rounded-2xl border border-border bg-white p-4"><summary className="cursor-pointer font-bold text-primary">+ સેવા પ્રવૃત્તિ</summary><ActivityForm categories={categories.filter(c=>!c.archived_at)} ashrams={ashrams}/></details></div>:null}

  <section className="mt-7"><div className="flex items-center gap-2"><HeartHandshake className="size-5 text-sacred-green"/><h2 className="font-serif text-xl font-bold text-primary">સેવા ક્ષેત્રો ({categories.length})</h2></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map(c=><article key={c.id} className={`rounded-2xl border bg-white p-4 ${c.archived_at?"border-dashed opacity-70":"border-border"}`}><p className="font-bold">{c.title_gu}</p><p className="mt-1 text-xs text-muted-foreground">{c.archived_at?"Archived":c.published?"પ્રકાશિત":"Draft"}</p>{manage&&!c.archived_at?<details className="mt-3 rounded-xl bg-[#f8f4ee] p-3"><summary className="cursor-pointer text-sm font-bold text-primary">Edit</summary><CategoryForm item={c}/></details>:null}{manage?<div className="mt-3 flex flex-wrap gap-2">{c.archived_at?<form action={restoreOperationalRecordAction}><input type="hidden" name="table" value="seva_categories"/><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-xs font-bold"><RotateCcw className="size-4"/>Restore</button></form>:<form action={archiveOperationalRecordAction}><input type="hidden" name="table" value="seva_categories"/><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-xs font-bold text-muted-foreground"><Archive className="size-4"/>Archive</button></form>}{superAdmin?<form action={permanentDeleteAction}><input type="hidden" name="table" value="seva_categories"/><input type="hidden" name="id" value={c.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-red-200 px-3 text-xs font-bold text-red-700"><Trash2 className="size-4"/>Delete</button></form>:null}</div>:null}</article>)}</div></section>

  <section className="mt-7"><h2 className="font-serif text-xl font-bold text-primary">પ્રવૃત્તિઓ ({activities.length})</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{activities.map(a=><article key={a.id} className={`rounded-2xl border bg-white p-4 ${a.archived_at?"border-dashed opacity-70":"border-border"}`}><p className="font-bold">{a.title_gu}</p><p className="mt-1 text-xs text-muted-foreground">{a.activity_date||"તારીખ વગર"} • {a.archived_at?"Archived":a.published?"પ્રકાશિત":"Draft"}</p>{manage&&!a.archived_at?<details className="mt-3 rounded-xl bg-[#f8f4ee] p-3"><summary className="cursor-pointer text-sm font-bold text-primary">Edit</summary><ActivityForm item={a} categories={categories.filter(c=>!c.archived_at)} ashrams={ashrams}/></details>:null}{manage?<div className="mt-3 flex flex-wrap gap-2">{a.archived_at?<form action={restoreOperationalRecordAction}><input type="hidden" name="table" value="seva_activities"/><input type="hidden" name="id" value={a.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-xs font-bold"><RotateCcw className="size-4"/>Restore</button></form>:<form action={archiveOperationalRecordAction}><input type="hidden" name="table" value="seva_activities"/><input type="hidden" name="id" value={a.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-xs font-bold text-muted-foreground"><Archive className="size-4"/>Archive</button></form>}{superAdmin?<form action={permanentDeleteAction}><input type="hidden" name="table" value="seva_activities"/><input type="hidden" name="id" value={a.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-red-200 px-3 text-xs font-bold text-red-700"><Trash2 className="size-4"/>Delete</button></form>:null}</div>:null}</article>)}</div>{!activities.length?<p className="mt-3 rounded-2xl border border-dashed border-border bg-white p-5 text-sm text-muted-foreground">હાલ કોઈ સેવા પ્રવૃત્તિ ઉમેરાઈ નથી. ઉપરથી ઉમેરેલી અને Publish કરેલી પ્રવૃત્તિ જાહેર website પર દેખાશે.</p>:null}</section>

  <section className="mt-7"><div className="flex items-center gap-2"><UserCheck className="size-5 text-primary"/><h2 className="font-serif text-xl font-bold text-primary">સ્વયંસેવક અરજીઓ ({volunteers.length})</h2></div><div className="mt-3 space-y-3">{volunteers.map(v=><article key={v.id} className="rounded-2xl border border-border bg-white p-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="font-bold">{v.full_name}</p><p className="mt-1 text-xs text-muted-foreground">{v.application_number} • {v.mobile} • {v.status}</p><p className="mt-2 text-sm text-muted-foreground">{v.time_slot||"સમય ન જણાવેલ"} {v.skills?`• ${v.skills}`:""}</p></div>{review?<form action={reviewVolunteerAction} className="grid min-w-[180px] gap-2"><input type="hidden" name="id" value={v.id}/><select className="field !min-h-10 text-xs" name="status" defaultValue={v.status}><option value="submitted">નવી</option><option value="contacted">સંપર્ક કર્યો</option><option value="confirmed">પુષ્ટિ</option><option value="completed">પૂર્ણ</option><option value="rejected">નામંજૂર</option><option value="archived">આર્કાઇવ</option></select><input className="field !min-h-10 text-xs" name="review_note" placeholder="આંતરિક નોંધ" defaultValue={v.review_note??""}/><button className="min-h-10 rounded-xl bg-[#eee7de] text-xs font-bold text-primary">સાચવો</button></form>:null}</div></article>)}</div></section>
  </div>;
}
