import Link from "next/link";
import { ArrowRight, BookOpenText, CalendarDays, HeartHandshake, Landmark, MapPin, Radio, ScrollText } from "lucide-react";

import { YouTubeMark } from "@/components/icons/youtube-mark";
import { YouTubeFacade } from "@/components/media/youtube-facade";
import { HomeHero } from "@/components/sections/home-hero";
import { HomeIdentityCard } from "@/components/sections/home-identity-card";
import { MadhavRekha } from "@/components/ui/madhav-rekha";
import { SectionHeading } from "@/components/ui/section-heading";
import { getPublicAshrams, getPublicSevaActivities, getPublicTithiProgrammes } from "@/lib/operations/public-data";
import { youtubeChannel, youtubeChannelId } from "@/lib/site-data";

const quickActions = [
  { icon: CalendarDays, label: "આગામી કાર્યક્રમો", note: "તારીખ અને સ્થળ જુઓ", href: "/events" },
  { icon: Radio, label: "સત્સંગ જુઓ", note: "અધિકૃત વિડિયો", href: "/satsang" },
  { icon: MapPin, label: "આશ્રમ શોધો", note: "આશ્રમ માહિતી", href: "/ashrams" },
  { icon: BookOpenText, label: "પ્રકાશનો વાંચો", note: "વેદ રહસ્ય સંગ્રહ", href: "/publications" },
];

const eventKind: Record<string,string> = {tithi:"તિથિ",satsang:"સત્સંગ",bal_shibir:"બાળ શિબિર",special:"વિશેષ",tour:"સ્વામીજી કાર્યક્રમ",poonam:"પૂનમ ઉત્સવ"};

export default async function HomePage() {
  const [events, ashrams, seva] = await Promise.all([getPublicTithiProgrammes(), getPublicAshrams(), getPublicSevaActivities()]);
  const upcoming = events.slice(0,3);
  const featuredAshrams = ashrams.slice(0,3);
  const featuredSeva = seva.slice(0,3);

  return <>
    <HomeHero />

    <section aria-label="ઝડપી સેવાઓ" className="relative z-10 bg-surface py-5 shadow-[0_10px_35px_rgba(72,45,28,.05)] sm:py-6"><div className="container-site grid grid-cols-2 gap-2.5 md:grid-cols-4 md:gap-3">{quickActions.map(({icon:Icon,label,note,href})=><Link key={href} href={href} className="group flex min-h-[6.5rem] flex-col justify-between rounded-2xl border border-border bg-background p-4 transition hover:border-gold/45 hover:bg-surface-soft sm:min-h-[7rem] sm:p-5"><Icon className="h-5 w-5 text-gold-deep" aria-hidden="true"/><span className="mt-3 font-serif text-[1.02rem] font-bold leading-snug text-primary sm:text-lg">{label}</span><span className="mt-1 hidden text-xs text-muted-foreground sm:block">{note}</span></Link>)}<HomeIdentityCard variant="compact" className="col-span-2 mt-2 md:col-span-4 lg:hidden"/></div></section>

    <section className="py-11 sm:py-16 lg:py-20"><div className="container-site"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="આગામી કાર્યક્રમ" title="આશ્રમ પરિવાર સાથે જોડાયેલા રહો" description="Admin માં સમિતિ દ્વારા પ્રકાશિત આગામી કાર્યક્રમો અહીં સીધા દેખાય છે."/><Link href="/events" className="inline-flex min-h-12 items-center gap-2 self-start rounded-full border border-border-strong bg-surface px-5 font-bold text-primary">બધા કાર્યક્રમો <ArrowRight className="size-4"/></Link></div>{upcoming.length?<div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{upcoming.map(item=><article key={item.id} className="card-sacred p-5"><div className="flex items-center justify-between gap-3 text-xs font-bold"><span className="text-gold-deep">{eventKind[item.programme_type]??item.programme_type}</span><span className="text-primary">{item.programme_date}</span></div><h3 className="mt-3 font-serif text-xl font-bold text-primary-strong">{item.title_gu}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.village_city_gu}{item.venue_gu?` • ${item.venue_gu}`:""}</p>{item.map_url?<a href={item.map_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-10 items-center gap-2 text-sm font-bold text-primary"><MapPin className="size-4"/>દિશા</a>:null}</article>)}</div>:<div className="mt-7 rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">હાલ કોઈ આગામી કાર્યક્રમ પ્રકાશિત નથી. Admin માં Publish થયા પછી અહીં દેખાશે.</div>}</div></section>

    <section className="border-y border-border/70 bg-surface py-11 sm:py-16 lg:py-20"><div className="container-site grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-center lg:gap-16"><SectionHeading eyebrow="ગુરુપરંપરા અને ઓળખ" title="ચાર દિશાઓ, એક સંતુલિત જીવનમાર્ગ" description="ધર્મ, ભક્તિ, જ્ઞાન અને વૈરાગ્ય — પરંપરાના આ ચાર આધારને આચરણ અને સ્વાધ્યાય સાથે જીવવાનો માર્ગ."/><MadhavRekha/></div></section>

    <section className="overflow-hidden bg-[#37151c] text-[#f8ece0]"><div className="container-site grid gap-10 py-16 md:py-20 lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:gap-16 lg:py-24"><div><div className="text-xs font-bold tracking-[.1em] text-[#e6ad56]">અધિકૃત YouTube સત્સંગ</div><h2 className="section-title mt-4 max-w-xl text-white">જ્યાં હો ત્યાંથી સત્સંગ સાથે જોડાઓ.</h2><p className="mt-5 max-w-xl text-[17px] leading-8 text-[#d9c8bb]">તાજા પ્રવચન અને કાર્યક્રમો અધિકૃત ચેનલ પર જુઓ.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link href="/satsang" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#f8ece0] px-5 font-bold text-primary"><Radio className="size-4"/>સત્સંગ જુઓ</Link><a href={youtubeChannel} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/25 px-5 font-bold text-white"><YouTubeMark className="size-4"/>YouTube ચેનલ</a></div></div><YouTubeFacade playlistId={`UU${youtubeChannelId.slice(2)}`} title="શ્રી માધવાનંદ આશ્રમના તાજા સત્સંગ" compact/></div></section>

    <section className="section-pad bg-surface"><div className="container-site"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="આશ્રમ પરિવાર" title="એક પરંપરા, અનેક કેન્દ્રો" description="સમિતિ દ્વારા પ્રકાશિત આશ્રમ માહિતી અહીંથી સીધી મળે છે."/><Link href="/ashrams" className="inline-flex min-h-12 items-center gap-2 self-start rounded-full bg-primary px-5 font-bold text-primary-foreground"><Landmark className="size-4"/>તમામ આશ્રમ જુઓ</Link></div>{featuredAshrams.length?<div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{featuredAshrams.map(a=><article key={a.id} className="card-sacred p-5"><p className="text-xs font-bold text-sacred-green">પ્રકાશિત આશ્રમ</p><h3 className="mt-2 font-serif text-xl font-bold text-primary-strong">{a.name_gu}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{a.full_address||[a.city_gu,a.state_gu].filter(Boolean).join(", ")}</p><div className="mt-4 flex flex-wrap gap-3 text-sm font-bold text-primary">{a.office_phone?<a href={`tel:${a.office_phone}`}>{a.office_phone}</a>:null}{a.map_url?<a href={a.map_url} target="_blank" rel="noreferrer">દિશા ↗</a>:null}</div></article>)}</div>:<p className="mt-7 rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">Admin માં આશ્રમ Publish થયા પછી અહીં દેખાશે.</p>}</div></section>

    <section className="section-pad border-y border-border/70"><div className="container-site"><SectionHeading eyebrow="સેવા એટલે સાધના" title="ભક્તિ જ્યારે સમાજ સુધી પહોંચે" description="Admin માં પ્રકાશિત સેવા પ્રવૃત્તિઓમાંથી તાજી પસંદગી."/>{featuredSeva.length?<div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{featuredSeva.map(activity=><article key={activity.id} className="card-sacred p-5"><HeartHandshake className="size-5 text-sacred-green"/><h3 className="mt-3 font-serif text-xl font-bold text-primary-strong">{activity.title_gu}</h3>{activity.summary_gu?<p className="mt-2 text-sm leading-6 text-muted-foreground">{activity.summary_gu}</p>:null}{activity.metric_value?<p className="mt-3 text-sm font-bold text-primary">{activity.metric_label_gu?`${activity.metric_label_gu}: `:""}{activity.metric_value}</p>:null}</article>)}</div>:<p className="mt-7 rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">પ્રકાશિત સેવા પ્રવૃત્તિઓ અહીં દેખાશે.</p>}<Link href="/seva" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full border border-border-strong bg-surface px-5 font-bold text-primary">બધી સેવા પ્રવૃત્તિઓ <ArrowRight className="size-4"/></Link></div></section>

    <section className="section-pad bg-[#f1e5d3]"><div className="container-site"><SectionHeading eyebrow="જ્ઞાન અને વારસો" title="વાંચનથી સંરક્ષણ સુધી" description="પ્રકાશન, ગુરુપરંપરા અને ઐતિહાસિક વારસાનો ડિજિટલ પ્રવેશ."/><div className="mt-9 grid gap-5 md:grid-cols-3">{[
      {icon:BookOpenText,title:"વેદ રહસ્ય અને પ્રકાશનો",copy:"ઉપલબ્ધ અંકો અને આધ્યાત્મિક પ્રકાશનો વાંચો.",href:"/publications",cta:"પ્રકાશનો વાંચો"},
      {icon:ScrollText,title:"વારસા સંગ્રહ",copy:"ઐતિહાસિક પત્રો અને ઉપલબ્ધ દસ્તાવેજ જુઓ.",href:"/heritage",cta:"વારસા જુઓ"},
      {icon:BookOpenText,title:"ગુરુપરંપરા",copy:"ગુરુપરંપરાની પ્રકાશિત માહિતી અને અધ્યાય વાંચો.",href:"/parampara",cta:"ગુરુપરંપરા જુઓ"},
    ].map(({icon:Icon,title,copy,href,cta})=><article key={href} className="rounded-2xl border border-primary/10 bg-[#fffaf3] p-6"><Icon className="size-6 text-gold-deep"/><h3 className="mt-4 font-serif text-xl font-bold text-primary-strong">{title}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{copy}</p><Link href={href} className="mt-5 inline-flex min-h-10 items-center gap-2 font-bold text-primary">{cta}<ArrowRight className="size-4"/></Link></article>)}</div></div></section>

    <section className="section-pad"><div className="container-site rounded-[1.5rem] border border-primary/15 bg-[#f6eee3] p-6 sm:p-8 lg:flex lg:items-center lg:justify-between lg:gap-10"><div className="max-w-2xl"><p className="eyebrow">પરિવાર સાથે જોડાઓ</p><h2 className="mt-3 font-serif text-3xl font-bold text-primary-strong">સત્સંગથી આત્મકલ્યાણ, સેવાથી સમાજકલ્યાણ</h2><p className="mt-3 text-[15px] leading-7 text-muted-foreground">સભ્યપદ, સ્વયંસેવક સેવા, ઉતારો અથવા અન્ય માર્ગદર્શન માટે સંબંધિત વિભાગ પસંદ કરો.</p></div><div className="mt-6 flex flex-wrap gap-3 lg:mt-0"><Link href="/membership" className="inline-flex min-h-12 items-center rounded-full bg-primary px-5 font-bold text-white">સભ્યપદ</Link><Link href="/volunteer" className="inline-flex min-h-12 items-center rounded-full border border-border-strong bg-white px-5 font-bold text-primary">સેવામાં જોડાઓ</Link><Link href="/stay" className="inline-flex min-h-12 items-center rounded-full border border-border-strong bg-white px-5 font-bold text-primary">ઉતારો</Link></div></div></section>
  </>;
}
