alter policy admin_profiles_self_or_admin_select on public.admin_profiles using ((id = (select auth.uid())) or private.has_permission('admin.view'));
alter policy assignments_self_or_admin_select on public.admin_role_assignments using ((admin_id = (select auth.uid())) or private.has_permission('admin.view'));
alter policy notes_insert on public.internal_notes with check ((author_id = (select auth.uid())) and private.has_permission('inbox.update'));
alter policy notes_update_own on public.internal_notes using ((author_id = (select auth.uid())) and private.has_permission('inbox.update')) with check (author_id = (select auth.uid()));
alter policy notifications_own_select on public.notifications using (admin_id = (select auth.uid()));
alter policy notifications_own_update on public.notifications using (admin_id = (select auth.uid())) with check (admin_id = (select auth.uid()));
alter policy admin_invitations_super_insert on public.admin_invitations with check (private.is_super_admin() and invited_by = (select auth.uid()));
alter policy cash_admin_insert on public.cash_transactions with check ((received_by = (select auth.uid())) and case when ashram_id is null then private.has_global_permission('cash.record') else private.has_ashram_permission('cash.record', ashram_id) end);
alter policy receipts_admin_insert on public.receipts with check ((issued_by = (select auth.uid())) and private.can_access_cash('receipts.issue', cash_transaction_id));
alter policy status_history_insert on public.status_history with check ((changed_by = (select auth.uid())) and private.is_active_admin());

create index if not exists admin_invitations_auth_user_idx on public.admin_invitations(auth_user_id);
create index if not exists admin_invitations_invited_by_idx on public.admin_invitations(invited_by);
create index if not exists admin_invitations_role_idx on public.admin_invitations(role_id);
create index if not exists admin_role_assignments_assigned_by_idx on public.admin_role_assignments(assigned_by);
create index if not exists admin_role_assignments_role_idx on public.admin_role_assignments(role_id);
create index if not exists ashram_profiles_created_by_idx on public.ashram_profiles(created_by);
create index if not exists booking_document_upload_tokens_created_by_idx on public.booking_document_upload_tokens(created_by);
create index if not exists booking_documents_guest_idx on public.booking_documents(guest_id);
create index if not exists booking_documents_stay_request_idx on public.booking_documents(stay_request_id);
create index if not exists cash_transactions_ashram_idx on public.cash_transactions(ashram_id);
create index if not exists cash_transactions_received_by_idx on public.cash_transactions(received_by);
create index if not exists cash_transactions_voided_by_idx on public.cash_transactions(voided_by);
create index if not exists donation_intents_assigned_to_idx on public.donation_intents(assigned_to);
create index if not exists donation_intents_preferred_ashram_idx on public.donation_intents(preferred_ashram_id);
create index if not exists guru_chapters_created_by_idx on public.guru_chapters(created_by);
create index if not exists guru_chapters_updated_by_idx on public.guru_chapters(updated_by);
create index if not exists guru_profiles_created_by_idx on public.guru_profiles(created_by);
create index if not exists heritage_documents_created_by_idx on public.heritage_documents(created_by);
create index if not exists households_created_by_idx on public.households(created_by);
create index if not exists households_primary_person_idx on public.households(primary_person_id);
create index if not exists internal_notes_author_idx on public.internal_notes(author_id);
create index if not exists internal_notes_inbox_item_idx on public.internal_notes(inbox_item_id);
create index if not exists media_assets_created_by_idx on public.media_assets(created_by);
create index if not exists media_folders_created_by_idx on public.media_folders(created_by);
create index if not exists media_folders_parent_idx on public.media_folders(parent_id);
create index if not exists membership_applications_approved_household_idx on public.membership_applications(approved_household_id);
create index if not exists membership_applications_reviewed_by_idx on public.membership_applications(reviewed_by);
create index if not exists memberships_created_by_idx on public.memberships(created_by);
create index if not exists memberships_primary_person_idx on public.memberships(primary_person_id);
create index if not exists programme_centres_ashram_idx on public.programme_centres(ashram_id);
create index if not exists programme_centres_created_by_idx on public.programme_centres(created_by);
create index if not exists programme_circulars_created_by_idx on public.programme_circulars(created_by);
create index if not exists receipts_issued_by_idx on public.receipts(issued_by);
create index if not exists receipts_voided_by_idx on public.receipts(voided_by);
create index if not exists role_permissions_permission_code_idx on public.role_permissions(permission_code);
create index if not exists roles_created_by_idx on public.roles(created_by);
create index if not exists room_assignments_assigned_by_idx on public.room_assignments(assigned_by);
create index if not exists room_blocks_created_by_idx on public.room_blocks(created_by);
create index if not exists room_blocks_room_idx on public.room_blocks(room_id);
create index if not exists room_types_ashram_idx on public.room_types(ashram_id);
create index if not exists rooms_room_type_idx on public.rooms(room_type_id);
create index if not exists seva_activities_ashram_idx on public.seva_activities(ashram_id);
create index if not exists seva_activities_category_idx on public.seva_activities(category_id);
create index if not exists seva_activities_created_by_idx on public.seva_activities(created_by);
create index if not exists seva_categories_created_by_idx on public.seva_categories(created_by);
create index if not exists status_history_changed_by_idx on public.status_history(changed_by);
create index if not exists stay_requests_assigned_to_idx on public.stay_requests(assigned_to);
create index if not exists tithi_programmes_ashram_idx on public.tithi_programmes(ashram_id);
create index if not exists tithi_programmes_created_by_idx on public.tithi_programmes(created_by);
create index if not exists veda_article_submissions_reviewed_by_idx on public.veda_article_submissions(reviewed_by);
create index if not exists veda_issues_created_by_idx on public.veda_issues(created_by);
create index if not exists veda_change_requests_reviewed_by_idx on public.veda_subscriber_change_requests(reviewed_by);
create index if not exists veda_subscribers_created_by_idx on public.veda_subscribers(created_by);
create index if not exists veda_subscription_applications_cash_idx on public.veda_subscription_applications(cash_transaction_id);
create index if not exists veda_subscription_applications_reviewed_by_idx on public.veda_subscription_applications(reviewed_by);
create index if not exists veda_subscription_applications_subscriber_idx on public.veda_subscription_applications(subscriber_id);
create index if not exists volunteer_applications_preferred_ashram_idx on public.volunteer_applications(preferred_ashram_id);
create index if not exists volunteer_applications_reviewed_by_idx on public.volunteer_applications(reviewed_by);
