"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { hasAdminPermission,requireAdminSession } from "@/lib/admin/data";
import { getAdminAccessToken,supabaseRest } from "@/lib/supabase/server";
const x=(fd:FormData,n:string,m=2000)=>{const v=String(fd.get(n)??"").trim();return v?v.slice(0,m):null};
async function ctx(p:string){const s=await requireAdminSession();if(!hasAdminPermission(s,p))throw new Error("Permission denied");const t=await getAdminAccessToken();if(!t)redirect("/admin/login");return{s,t}}
export async function reviewVedaApplicationAction(fd:FormData){const{s,t}=await ctx("veda.subscriptions.manage");const id=x(fd,"id",40),status=x(fd,"status",30);if(!id||!status)return;await supabaseRest(`veda_subscription_applications?id=eq.${id}`,t,{method:"PATCH",prefer:"return=minimal",body:JSON.stringify({status,review_note:x(fd,"review_note",1000),reviewed_by:s.profile?.id,reviewed_at:new Date().toISOString()})});revalidatePath("/admin/veda")}
export async function reviewVedaChangeAction(fd:FormData){const{s,t}=await ctx("veda.subscriptions.manage");const id=x(fd,"id",40),status=x(fd,"status",30);if(!id||!status)return;await supabaseRest(`veda_subscriber_change_requests?id=eq.${id}`,t,{method:"PATCH",prefer:"return=minimal",body:JSON.stringify({status,review_note:x(fd,"review_note",1000),reviewed_by:s.profile?.id,reviewed_at:new Date().toISOString()})});revalidatePath("/admin/veda")}
export async function reviewVedaArticleAction(fd:FormData){const{s,t}=await ctx("veda.editorial.manage");const id=x(fd,"id",40),status=x(fd,"status",30);if(!id||!status)return;await supabaseRest(`veda_article_submissions?id=eq.${id}`,t,{method:"PATCH",prefer:"return=minimal",body:JSON.stringify({status,review_note:x(fd,"review_note",1000),reviewed_by:s.profile?.id,reviewed_at:new Date().toISOString()})});revalidatePath("/admin/veda")}
export async function activateVedaAction(fd:FormData){const{t}=await ctx("veda.approve");const id=x(fd,"id",40);if(id)await supabaseRest("rpc/activate_veda_subscription",t,{method:"POST",body:JSON.stringify({target_application_id:id}),prefer:"return=representation"});revalidatePath("/admin/veda")}
export async function saveVedaIssueAction(fd:FormData){const{s,t}=await ctx("veda.issues.manage");const id=x(fd,"id",40),published=fd.get("published")==="on";if(published&&!hasAdminPermission(s,"veda.issues.publish"))throw new Error("Publish permission required");const date=x(fd,"issue_date",10);if(!date)return;const d=new Date(`${date}T00:00:00Z`);const row={issue_date:date,issue_year:d.getUTCFullYear(),issue_month:d.getUTCMonth()+1,title_gu:x(fd,"title_gu",200)??"વેદ રહસ્ય",pdf_url:x(fd,"pdf_url",1000),cover_url:x(fd,"cover_url",1000),source_url:x(fd,"source_url",1000),published,archived_at:null};if(id)await supabaseRest(`veda_issues?id=eq.${id}`,t,{method:"PATCH",body:JSON.stringify(row),prefer:"return=minimal"});else await supabaseRest("veda_issues",t,{method:"POST",body:JSON.stringify({...row,created_by:s.profile?.id}),prefer:"return=minimal"});revalidatePath("/admin/veda");revalidatePath("/veda-rahasya")}
export async function archiveVedaIssueAction(fd:FormData){const{s,t}=await ctx("veda.issues.manage");if(!hasAdminPermission(s,"veda.issues.publish"))throw new Error("Publish permission required");const id=x(fd,"id",40);if(id)await supabaseRest(`veda_issues?id=eq.${id}`,t,{method:"PATCH",body:JSON.stringify({archived_at:new Date().toISOString(),published:false}),prefer:"return=minimal"});revalidatePath("/admin/veda");revalidatePath("/veda-rahasya")}
