import { ShieldCheck } from "lucide-react";

import { saveRolePermissionsAction } from "@/app/admin/actions";
import { getPermissions, getRolePermissionCodes, getRoles, requireAdminSession } from "@/lib/admin/data";

export default async function AdminRolesPage() {
  const session = await requireAdminSession();
  const [roles, permissions, rolePermissionCodes] = await Promise.all([getRoles(session), getPermissions(session), getRolePermissionCodes(session)]);
  return <div><p className="text-xs font-bold text-gold-deep">ACCESS CONTROL</p><h1 className="mt-1 font-serif text-2xl font-bold text-primary sm:text-3xl">ભૂમિકા અને પરવાનગીઓ</h1><p className="mt-1 text-sm text-muted-foreground">મુખ્ય એડમિન નક્કી કરે કે કયા એડમિનને શું જોવું અને બદલવું મળે.</p><div className="mt-5 space-y-4">{roles.map((role) => <form key={role.id} action={saveRolePermissionsAction} className="rounded-2xl border border-[#dfd9d0] bg-white p-4 shadow-sm sm:p-5"><input type="hidden" name="role_id" value={role.id} /><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#f3e8df] text-primary"><ShieldCheck className="size-[18px]" /></div><div><h2 className="font-serif text-lg font-bold text-primary">{role.name_gu}</h2><p className="text-xs text-muted-foreground">{role.name_en}{role.description_gu ? ` • ${role.description_gu}` : ""}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{permissions.map((permission) => <label key={permission.code} className={`flex min-h-12 items-start gap-2 rounded-xl border p-3 text-xs ${permission.dangerous ? "border-red-100 bg-red-50/50" : "border-[#e8e2da] bg-[#fbfaf7]"}`}><input type="checkbox" name="permission" value={permission.code} defaultChecked={(rolePermissionCodes[role.id] ?? []).includes(permission.code)} disabled={!session.profile?.is_super_admin} className="mt-0.5 size-4 accent-[#711f2d]" /><span><strong className="block text-[#413831]">{permission.name_gu}</strong><span className="mt-0.5 block leading-5 text-muted-foreground">{permission.code}</span></span></label>)}</div>{session.profile?.is_super_admin ? <button className="mt-4 min-h-10 rounded-xl bg-primary px-4 text-xs font-bold text-white" type="submit">પરવાનગીઓ સાચવો</button> : <p className="mt-4 text-xs font-semibold text-muted-foreground">ફેરફાર ફક્ત Super Admin કરી શકે.</p>}</form>)}</div></div>;
}
